### ISSUE TITLE
Inhoudelijke vraag: Creator van een dataset

### ISSUE THREAD

**Issue by RemieJanssen** [Geonovum/DCAT-AP-NL30#103]
De `creator` van een dataset moet nu een organisatie zijn, en er mag er maar een zijn. Als ik als maker van een dataset persoonlijke attributie wil toevoegen, waar doe ik dat dan? Dit kan van belang zijn voor herleidbaarheid, verantwoording, en ook voor aansluiting op wetenschappelijke processen (e.g. publicatie).

**Comment by idevisser** [comment]
In het NL profiel hebben we creator zodanig geformuleerd dat het een organisatie moet zijn en hebben we de voor de classe Agent de voorgestelde properties uit DCAT-AP overgenomen, Dit lijkt nu bij nadere bestudering niet helemaal logisch in elkaar te zitten. Het verplicht stellen van de property name lijkt een ongelukkige keuze. 

Voor de toepassing die jij aangeeft zouden we het NL profiel zodanig moeten aanpassen dat gebruik van de subclasse [foaf:Organization](http://xmlns.com/foaf/0.1/Organization) verplicht is en [foaf:Person](http://xmlns.com/foaf/0.1/Person) optioneel mogelijk is. Daarmee zijn we dan niet wat DCAT-AP conform. Of zie jij betere oplossingen?

**Comment by RemieJanssen** [comment]
Ik begrijp niet precies wat het probleem is. De situaties die ik beschreef passen uitstekend binnen DCAT-AP. In DCAT-AP is de definitie namelijk 
> "An entity responsible for producing the dataset."

In tegenstelling tot de beschrijving in van creator in DCAT-AP-NL hoeft het dus geen organisatie te zijn, zie paragraaf 3.1.5: 
> "De organisatie die verantwoordelijk is voor het creëren van de beschreven dataset. Gebruik bij voorkeur een URI of anders een waarde uit een organisatienamenlijst. Als dat niet mogelijk is, gebruik de volledig uitgeschreven naam van de verantwoordelijke organisatie. De afkorting kan toegevoegd worden aan de organisatienaam."

Wel is er een aanbeveling om uit de Organisation Ontology te kiezen ALS de agent een organisatie is ([Usage note](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Agent)).

Wat betreft het bereik van de eigenschap is het ook eenvoudig om gewoon DCAT-AP aan te houden. Die gebruikt namelijk een `foaf:Agent`, zoals jullie nu ook doen. De klassen `foaf:Person` en `foaf:Organization` zijn onderklassen van `foaf:Agent`, dus het gebruik van `foaf:Person` en `foaf:Organization` zijn beide correct. ([Agent doc](http://xmlns.com/foaf/spec/#term_Agent))

## Samenvatting

Het gaat mij om het aanpassen van de tekstuele beschrijving in 3.1.5, en het aanpassen van de kardinaliteit van de eigenschap naar `1..*`. Op de typo in de tabel onder `Description` na (`Ae entity...`), zie ik verder geen problemen met de technische beschrijving van de eigenschap creator.

**Comment by idevisser** [comment]
Waar ik op doelde is dat de status van de property [name](foaf:name) testing is en de specificatie dateert uit 2014. Dan verwacht je inmiddels toch  wel een stable status. Maar dat lijkt geen probleem.

**De vraag is of we hier in ieder geval een organisatie willen zien, eventueel met één of meerdere personen of dat het ook alleen personen kunnen zijn.** 

Als het in ieder geval een organisatie moet zijn dan kan het voor validatie handig zijn om dat specifiek te maken door foaf:Organization verplicht te stellen.

**Comment by jambelien** [comment]
> Ik begrijp niet precies wat het probleem is. De situaties die ik beschreef passen uitstekend binnen DCAT-AP. In DCAT-AP is de definitie namelijk
> 
> > "An entity responsible for producing the dataset."
> 
> In tegenstelling tot de beschrijving in van creator in DCAT-AP-NL hoeft het dus geen organisatie te zijn, zie paragraaf 3.1.5:
> 
> > "De organisatie die verantwoordelijk is voor het creëren van de beschreven dataset. Gebruik bij voorkeur een URI of anders een waarde uit een organisatienamenlijst. Als dat niet mogelijk is, gebruik de volledig uitgeschreven naam van de verantwoordelijke organisatie. De afkorting kan toegevoegd worden aan de organisatienaam."
> 
> Wel is er een aanbeveling om uit de Organisation Ontology te kiezen ALS de agent een organisatie is ([Usage note](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Agent)).
> 
> Wat betreft het bereik van de eigenschap is het ook eenvoudig om gewoon DCAT-AP aan te houden. Die gebruikt namelijk een `foaf:Agent`, zoals jullie nu ook doen. De klassen `foaf:Person` en `foaf:Organization` zijn onderklassen van `foaf:Agent`, dus het gebruik van `foaf:Person` en `foaf:Organization` zijn beide correct. ([Agent doc](http://xmlns.com/foaf/spec/#term_Agent))
> ## Samenvatting
> 
> Het gaat mij om het aanpassen van de tekstuele beschrijving in 3.1.5, en het aanpassen van de kardinaliteit van de eigenschap naar `1..*`. Op de typo in de tabel onder `Description` na (`Ae entity...`), zie ik verder geen problemen met de technische beschrijving van de eigenschap creator.

Redactioneel: kardinalitiet is aangepast maar Typo in Description 'Ae entity..' -> 'An entity..' nog verbeteren

**Comment by idevisser** [comment]
In WG twee punten besproken
o	Moet creator altijd een organisatie zijn. Besluit was dat we het laten zoals het is. Dwz dat we hier altijd een organsiatie verwachten. Besproken. 
	Use case. Bij wetenschappelijk publicaties zou dat ook een persoon kunnen zijn. 
	AVG. Liever geen persoonsgebonden gegevens opslaan
	Als je toch een persoon zou willen opgegeven  zou dat evt via asRole kunnen. 
	Optie voorgelegd: Organisatie minimaal verplicht eventueel optiioneel persoon. Echter besloten laten zoals het is. 
	--- OPM Jan --- M.i. wordt hier nu niks hard over afgedwongen – tenzij DONL straks bepaalde waardelijsten verplicht gaat stellen e daarop gaat valideren. 
o	Kardinalitiet Creator. Was in versie 16 april 1..1. In WG besloten dat die 1..n wordt. Dat staat inmiddels al zo in DCAT-AP-NL
	Use Case. Vanuit wetenschap / health. Situatie bestaat dat er samenwerkingsverbanden bestaan tussen organisatie die samen een dataset maken. In dat geval wil je meerder creators voor de Dataset kunnen opgeven. 
	Besluit
•	Dataset creator. Van 1..1 naar 1..n . Geen aanpassing nodig. Dat is inmiddels al zo verwerkt in de werkversie van DCAT-AP-NL
•	Dataservice Creator. Was 0..1 en blijft 0..1. Geen aanpassing nodig
•	Catalogue Creator.  Was 0..1 en blijft 0..1. Geen aanpassing nodig

**Comment by skornsekj** [comment]
De typo in description komt niet meer voor.
