### ISSUE TITLE
Editorial: toevoegen afkortingen voor verplicht, aanbevolen, optioneel en conditioneel tbv gebruik in tabellen

### ISSUE THREAD

**Issue by jambelien** [Geonovum/DCAT-AP-NL30#11]
In paragraaf https://docs.geostandaarden.nl/dcat/dcat-ap-nl30/#5679FE7C (2.3 Optionaliteit) staat nu de zin: In de volgende secties worden klassen en eigenschappen aangeduid als "verplicht", "aanbevolen", "optioneel" of conditioneel. 
In de eerste daarop volgende tabel (https://docs.geostandaarden.nl/dcat/dcat-ap-nl30/#dataset-dcat-dataset 3.1 Dataset - dcat:Dataset) staan in de kolom Optionaliteit de volgende gebruikte afkortingen: V, O. A, C.

Voorgestelde wijiziging: 
vervang de zin: In de volgende secties worden klassen en eigenschappen aangeduid als "verplicht", "aanbevolen", "optioneel" of conditioneel.
door de zin: In de volgende secties worden klassen en eigenschappen aangeduid als "verplicht" (V), "aanbevolen" (A), "optioneel" (O) of conditioneel (C), waarbij de tussen de haakjes opgenomen hoofdletter als afkorting wordt gebruikt.
Prioriteit issue: Nice to have.

**Comment by vanmeule** [comment]
Ik wilde dezelfde aanpassing voorstellen.

**Comment by CorMelse** [comment]
Ik ook ;-)

**Comment by idevisser** [comment]
aangepast
