### ISSUE TITLE
INHOUDELIJK: Onvolledige specificatie van te gebruiken waardelijsten

### ISSUE THREAD

**Issue by hoverbee** [Geonovum/DCAT-AP-NL30#110]
In sectie 5 van de Consultatieversie DCAT-AP NL van 16 april 2024 is de toelichting op de te gebruiken waardelijsten vrijwel volledig gericht op de voorschriften uit DCAT-AP voor de verplichte EU-waardelijsten. 

Dat is op zich correct, want één van de uitgangspunten is dat DCAT-AP-NL de uitwisseling faciliteert van metadata tussen Nederlandse datacatalogi en EU datacatalogi. Het citeren van EU-specificaties is wel handig voor het overzicht, dus ik ben daar ook voor, maar in feite overbodig, omdat ook verwezen kan worden naar DCAT-AP. En het moet duidelijk zijn of de specificatie 1 op 1 wordt overgenomen of in DCAT-AP-NL is aangepast. (zie in dat verband ook issue #20)

Er wordt in sectie 5 echter niet duidelijk dat NAAST de EU-waardelijsten ook andere waardelijsten gehanteerd kunnen worden. Sterker nog: in het belang van de andere uitgangspunten van DCAT-AP NL zouden die voorschriften dwingender mogen zijn.

DCAT-AP NL faciliteert:
- de uitwisseling van metadata tussen Nederlandse datacatalogi van (semi-) overheidsorganisatie en overige organisaties die maatschappelijke relevante data willen delen.
- de uitwisseling van metadata van primair open data, maar is hier niet toe beperkt
- de specifieke Nederlandse behoeften van metadata in datacatalogi

Voor Nederlandse toepassingen kunnen andere waardelijsten worden aanbevolen of voorgeschreven, zoals de waardelijsten van TOOI of OWMS voor thema en publisher (zie in dat verband ook https://github.com/Geonovum/DCAT-AP-NL30/issues/16). Elders in DCAT-AP NL worden meer alternatieve waardelijsten genoemd, maar die zijn niet opgenomen in sectie 5. Dat zou wel overzichtelijk zijn.

In DCAT-AP NL moet wel duidelijk worden wat de verplichting is voor EU en wat de verplichting is voor NL.

**Comment by idevisser** [comment]
Voorstel in hoofdstuk 5 ook de andere waardelijsten die worden aanbevolen of voorgeschreven opnemen

**Comment by skornsekj** [comment]
De aanbevolen waardelijsten zijn in hoofdstuk 5 opgenomen
