### ISSUE TITLE
Inhoudelijk: toevoegen van nieuwe databestandsformaten aan 

### ISSUE THREAD

**Issue by dkapitan** [Geonovum/DCAT-AP-NL30#114]
# Betreft volgende paragrafen / klassen

- Distribution 3.2.11 format range
- DataService 3.3.10 format range

# Omschrijving

Op bovenstaande plaatsen wordt verwezen naar [de EU lijst van bestandsformaten](http://publications.europa.eu/resource/authority/file-type). Ik constateer dat de meest moderne, efficiente bestandstandformaten ontbreken, te weten:

- [Apache Parquet](https://parquet.apache.org/)
- [Apache AVRO](https://avro.apache.org/)
- [Apache ORC](https://orc.apache.org/docs/)

# Prioriteit
Must-have

# Voorgestelde aanpassing
Bovengenoemde formaten toevoegen aan de waardelijst

**Comment by idevisser** [comment]
verzoek bij EU publication office ingediend

**Comment by idevisser** [comment]
@dkapitan ik heb verzoek ingediend, kun jij gevraagde info geven? zie hieronder:


Thank you for your proposal to add new file type concepts. We would be happy to add them in our next release, if you could provide some more information.

You suggest to add Apache Parquet, Apache AVRO and Apache ORC.

In the File type authority table, a mandatory property for each concept is the [IANA](https://www.iana.org/assignments/media-types/media-types.xhtml) media type and preferably also a file extension. It is possible to have several media types. 

In the IANA currently there are these six media types listed for Apache:

application/vnd.apache.parquet, file extension: .parquet
application/vnd.apache.thrift.binary, file extension: n/a
application/vnd.apache.thrift.compact, file extension: n/a
application/vnd.apache.thrift.json, file extension: n/a
application/vnd.apache.arrow.file, file extension: .arrow
application/vnd.apache.arrow.stream, file extension: .arrows

So, for the Apache Parquet we have the necessary information, but not for other two. 
We had a look at the specifications, but it was not clear.

Do you know what file format are AVRO and ORC files based on – text, binary, json, xml? 
We can use one or more generic media types, if there is no specific one, but at least one media type is necessary. Perhaps there is a generic media type for columnar database formats?

Looking forward to you feedback!

**Comment by idevisser** [comment]
ik heb je feedback doorgegeven aan het EU publication office

**Comment by idevisser** [comment]
Er is verder geen aanpassing nodig in dit profiel.
