### ISSUE TITLE
Editorial: headings in tabel bij paragraaf 3.1 Dataset - dcat:Dataset zijn nu mix van engelse en nederlandse termen

### ISSUE THREAD

**Issue by jambelien** [Geonovum/DCAT-AP-NL30#12]
In paragraaf https://docs.geostandaarden.nl/dcat/dcat-ap-nl30/#dataset-dcat-dataset (3.1 Dataset - dcat:Dataset) worden in de kolom headings nu zowel engelse als nederlandse termen gebruikt (
Property | URI | Range | Card | Optionaliteit
-- | -- | -- | -- | --

) en bovendien is de ene term volledig uitgeschreven en de ander een afkorting.
Voorgestelde aanpassing:
1) of consequent voor de kolom namen de engesle termen gebruiken en dus Optionalitiet vervangen door Conformance, of alle engelse door nederlandse vervangen.
2) Card is afgekort, voorstel om dat voluit te schrijven ->Cardinality (of de nederlandse term (zie 1) hierboven) Kardinaliteit

pritoirteit: nice to have

**Comment by RemieJanssen** [comment]
Hetzelfde geldt voor de rijen in de subsecties van 3.1. Ook daar staan de Engelse termen property, cardinality, en range.

Daarnaast geldt dit ook voor alle andere klassen in Hoofdstuk 3.

**Comment by skornsekj** [comment]
Voorstel is voor de kolom namen alleen Nederlandse termen te gebruiken: Eigenschap, URI, Bereik, Kardinaliteit, Optionaliteit. Dat wordt aangepast.

**Comment by skornsekj** [comment]
Kolomtitels zijn aangepast.
