### ISSUE TITLE
Editorial: termen MAG MOET en MOETEN in paragraaf Confromiteit, SHOULD vertalen naar BEHOORT

### ISSUE THREAD

**Issue by jambelien** [Geonovum/DCAT-AP-NL30#121]
Paragraaf: Conformitiet
Type issue: redactioneel/inhoudelijk
Korte omschrijving van het issue: vertaling SHOULD -> MOETEN is verwarrend en eerder afgesproken (zie ook PFDs meetings) dat het BEHOORT is
Prioriteit issue:  Must-Have
Voorgestelde aanpassing: voor de volledgheid alle vier de termen
- MAY -> MAG
- MUST -> MOET
- SHOULD -> BEHOORT
- SHOULD NOT -> BEHOORT NIET

**Comment by skornsekj** [comment]
De volgende tekst wordt verwijderd uit de paragraaf conformiteit. 

De trefwoorden MAG, MOET en MOETEN in dit document moeten worden geïnterpreteerd als in [BCP 14](https://tools.ietf.org/html/bcp14) [[RFC2119](https://geonovum.github.io/DCAT-AP-NL30/#bib-rfc2119)] [[RFC8174](https://geonovum.github.io/DCAT-AP-NL30/#bib-rfc8174)] als, en alleen als deze in hoofdletters zijn weergegeven, zoals hier getoond.

**Comment by NielsHoffmann** [comment]
conformance section verwijderd

**Comment by NielsHoffmann** [comment]
In de logius respec code lijkt SHOULD als ZAL vertaald te worden. Ik kan alleen niet volgen waarom die termen niet in de conformance sectie verschijnen.
