### ISSUE TITLE
Editroial: , vervangen door . in Inleiding

### ISSUE THREAD

**Issue by jambelien** [Geonovum/DCAT-AP-NL30#122]
Paragraaf: Inleiding
Type issue: redactioneel
Korte omschrijving van het issue: , vervangen door .
Prioriteit issue:  Nice-to-Have
Voorgestelde aanpassing:
- zinnen : Dit profiel faciliteert de uitwisseling van metadata van verschillende domeinen tussen Nederlandse datacatalogi van (semi)overheidsorganisaties op lokaal, regionaal en landelijk nivo en tussen Nederlandse datacatalogi en EU datacatalogi, Het definieert het schema en geeft voorbeelden voor het gebruik ervan. 
- vervangen door zinnen: Dit profiel faciliteert de uitwisseling van metadata van verschillende domeinen tussen Nederlandse datacatalogi van (semi)overheidsorganisaties op lokaal, regionaal en landelijk nivo en tussen Nederlandse datacatalogi en EU datacatalogi. Het definieert het schema en geeft voorbeelden voor het gebruik ervan.

**Comment by idevisser** [comment]
aangepast
