### ISSUE TITLE
Editorial: zin herschrijven in Inleiding en wat spreken we af mbt DCAT-AP NL

### ISSUE THREAD

**Issue by jambelien** [Geonovum/DCAT-AP-NL30#123]
Paragraaf: Inleiding
Type issue: redactioneel
Korte omschrijving van het issue: zin herschrijven en afkorting DCAT-AP NL overal consequent hetzelfde schrijven
Prioriteit issue:  Nice-to-Have
Voorgestelde aanpassing:
- zin: Dit Nederlandse applicatieprofiel - DCAT-AP NL- beantwoordt de vraag over hoe [[DCAT-AP-3.0](https://docs.geostandaarden.nl/dcat/dcat-ap-nl30/#bib-dcat-ap-3.0)] in de praktijk wordt toegepast Nederland.
- herschrijven naar: Dit Nederlandse applicatieprofiel - DCAT-AP-3.0 NL - beantwoordt de vraag over hoe [[DCAT-AP-3.0](https://docs.geostandaarden.nl/dcat/dcat-ap-nl30/#bib-dcat-ap-3.0)] in de Nederlandse praktijk wordt toegepast.
- In gehele re-spec document consequent DCAT-AP-NL of DCAT-AP Nl gebruiken. Vraag bovendien is of DCAT-AP-NL beter kan worden vervangen door DCAT-AP-3.0 NL, gelijk hoe we het DCAT-AP-3.0 EU profiel schrijven. Dan is meteen duidelijk dat het omm 3.0 gaat. Indien niet dan wel overal consequent of DCAT-AP NL of DCAT-AP-NL gebruiken (zie ijvoorbeeld figuur 1m, daar bevat de legenda/figuur titel DCAT-AP-NL terwijl figuur zelf DCAT-AP NL bevat

**Comment by idevisser** [comment]
zie ook https://github.com/Geonovum/DCAT-AP-NL30/issues/82

inleiding aangepast
