### ISSUE TITLE
Editorial: zin in Uitgangspunten herschrijven

### ISSUE THREAD

**Issue by jambelien** [Geonovum/DCAT-AP-NL30#124]
Paragraaf: Uitgangspunten
Type issue: redactioneel
Korte omschrijving van het issue: zin herschrijven
Prioriteit issue: Nice-to-Have
Voorgestelde aanpassing:
- de zin: Bij het opstellen zijn van het applicatie profiel zijn volgende uitgangspunten gehanteerd: 
- vervangen door: Bij het opstellen van het applicatie profiel zijn de volgende uitgangspunten gehanteerd:

**Comment by idevisser** [comment]
aangepast
