### ISSUE TITLE
Editorial:  Namespaces, broken link dcatap http://data.europa.eu/r5r/

### ISSUE THREAD

**Issue by jambelien** [Geonovum/DCAT-AP-NL30#125]
Paragraaf: Namespaces, tabel 
Type issue: Inhoudelijk
Korte omschrijving van het issue: broken of verkeerde link
Prioriteit issue:  Must-Have
Voorgestelde aanpassing:
- huidige link: http://data.europa.eu/r5r/
- vervangen door juiste (ik weet niet welke dat zou moeten zijn...)

**Comment by idevisser** [comment]
deze link is overgenomen uit DCAT-AP. Lijkt correcte link, maar deze resolved niet. Probleem is bij DCAT-AP ingeschoten.

**Comment by skornsekj** [comment]
Opgelost in laatste versie van DCAT-AP en verwerkt in DCAT-AP-NL.
