### ISSUE TITLE
Inhoudelijk: Onduidelijkheid over wat onder de cataloguslicentie valt

### ISSUE THREAD

**Issue by niehues** [Geonovum/DCAT-AP-NL30#127]
- Paragraaf 3.4.12, klasse: Catalog, property: licence
- Type issue: Inhoudelijk
- Korte omschrijving van het issue / probleem: Het is niet helemaal duidelijk of de licentie van de catalogus alleen geldt voor de resourcebeschrijvingen in de catalogus, of ook voor de resources zelf. Ik zou denken dat de licentie alleen van toepassing is op de resourcebeschrijvingen, maar ik denk dat dat niet duidelijk is.
- Prioriteit issue: Must-Have
- Voorgestelde aanpassing: Specificeer expliciet waarop de licentie van toepassing is

**Comment by idevisser** [comment]
Dit heeft inderdaad betrekking op de resource beschrijvingen in de catalogus. In de beschrijving van een distributie of dataservice wordt de licentie opgenomen die geldt voor de resource zelf. 

tekst is aangepast om dit te verduidelijken
