### ISSUE TITLE
Implementatie/Adaptatie voor 'geo-domein' 

### ISSUE THREAD

**Issue by BregjeBrugman** [Geonovum/DCAT-AP-NL30#128]
DCAT staat, net als de Nederlandse profielen van ISO 19115/19119, op de pas-toe-of-leg-uit lijst. Voor adaptatie in het geo-domein is het nodig om duidelijke afspraken te maken welke standaard in Nederland gebruikt gaat worden voor het geo-domein. Daarbij moeten de ‘geo’-registers die DCAT (nu) niet ondersteunen, als het NGR en Inspire Geoportal, DCAT gaan ondersteunen. 

Het centraal beschikbaar stellen van een mapping tussen de Nederlandse profielen van ISO 19115/19119 en de DCAT-AP-NL zou nuttig zijn voor implementatie van DCAT-AP-NL.

Aanbeveling voor document:

1. In de inleiding duidelijk maken dat de DCAT-AP-NL ook voorzien is voor de beschrijving van ruimtelijke datasets, en inzichtelijk maken hoe DCAT-AP-NL zich verhoudt tot de Nederlandse profielen van ISO 19115/19119.

**Comment by idevisser** [comment]
Aan een mapping van ISO 19115/19119 (INSPIRE ) naar de DCAT-AP wordt nog gewerkt in Europa. Dat is het geoDCAT profiel.  Als dat afgerond is kan er eventueel nog specifiek voor Nederland daar een aanvulling op worden gedaan. 

DCAT-AP-NL is een generieke uitwisseling standaard, waar aanvullend domein specifieke profielen zoals geoDCAT en healthDCAT op gemaakt kunnen worden. Dit zal  in de tekst duidelijker naar voren moeten komen.

**Comment by idevisser** [comment]
aangepast
