### ISSUE TITLE
Relatie DCAT-AP-NL met geoDCAT-AP

### ISSUE THREAD

**Issue by BregjeBrugman** [Geonovum/DCAT-AP-NL30#129]
In het document komt duidelijk naar voren dat de vereisten uit de HVD zijn meegenomen in deze versie, belangrijk is ook dat het Nederlands profiel van DCAT is afgestemd met de INSPIRE vereisten. Dit is op Europees niveau gedaan in het geoDCAT profiel, maar volgens figuur 1 is geoDCAT niet meegenomen in voorliggend profiel. Het zou zeer wenselijk zijn dat DCAT-AP-NL is afgestemd met de INSPIRE vereisten, het lijkt logisch dat dat gebeurt via het Europese geoDCAT. In het document wordt hier niets over gezegd. 
Alleen in figuur 1 is geoDCAT-AP opgenomen. Waarbij het afgeleide Nederlandse profiel geoDCAT-AP-NL is gepositioneerd als een oude of concept versie. 

Aanbeveling: 
1. In document duidelijk maken of INSPIRE vereisten zijn meegenomen, en hoe de relatie met geoDCAT-AP is (voorzien).
2. In figuur 1 duidelijk maken of geoDCAT-AP-NL een oude of concept versie betreft.

**Comment by idevisser** [comment]
Op dit moment wordt  op Europees niveau gewerkt aan het geoDCAT profiel, voor versie 3 van DCAT en DCAT-AP. Anders dan HVD, zijn de vereisten voor geoDCAT domein specifiek, daarom is het logisch dit in een apart profiel op te nemen. (net als Health DCAT, mobility DCAT etc.)  DCAT-AP-NL wordt voor zover mogelijk zodanig afgestemd met geoDCAT, dat de specifieke requirements voor geoDCAT niet strijdig zijn met DCAT-AP-NL en het geoDCAT profiel aanvullend op DCAT-AP-NL kan worden toegepast.

In dit profiel deze  aanpak duidelijk maken in beschrijving en plaatje bij Relatie andere profielen.

**Comment by idevisser** [comment]
aangepast
