### ISSUE TITLE
Editorial: aanpassen beschrijving https://docs.geostandaarden.nl/dcat/dcat-ap-nl30/#dataset-distribution i.v.m. conformance C en verplichtheid bij HVD

### ISSUE THREAD

**Issue by jambelien** [Geonovum/DCAT-AP-NL30#13]
In paragraaf https://docs.geostandaarden.nl/dcat/dcat-ap-nl30/#dataset-distribution (3.1.6 dataset distribution) staat nu de volgende beschrijving: Een distributie is de werkelijke data van de dataset in een bepaald formaat of een bepaalde aanbiedingsvorm. Een dataset kan meerdere distributies hebben, bijvoorbeeld via een API of directe download in verschillende formaten.
Als conformance heeft deze eigenschap C (Conditioneel) welke uit de beschrijving niet direct duidelijk is. De C heeft te maken met de HVD. Zodra een dataset HVD is dan is deze eigenschap verplicht.
Voorgestelde wijziging: Extra zin toevoegen, bijvoorbeeld: Het opgeven van de eigenschap dataset distribution is verplicht voor HVD.
prioriteit issue: Nice to have

**Comment by CorMelse** [comment]
Eens met @jambelien , maar dan generiek toe te passen bij alle C eigenschappen waar het een relatie heeft met de HVD.
het komt op meer plaatsen voor en ik moest ook even doorzoeken voordat ik het snapte ;-)

**Comment by idevisser** [comment]
is aangepast
