### ISSUE TITLE
DatasetSeries (figuur 2)

### ISSUE THREAD

**Issue by BregjeBrugman** [Geonovum/DCAT-AP-NL30#130]
In de titel van figuur 2 staat dat de DatasetSeries nog moeten worden toegevoegd. Het is niet duidelijk waarom ze ontbreken; zijn de DatasetSeries buiten scope van dit profiel, of is de figuur niet bijgewerkt? Aangezien datasetSeries wel zijn opgenomen in het voorliggende profiel (paragraaf 3.6) neem ik aan dat datasetSeries wel binnen scope van dit profiel zijn. 

Aanbeveling

1. Figuur 2 graag bijwerken in de versie ter vaststelling

**Comment by idevisser** [comment]
aangepast
