### ISSUE TITLE
Editorial: zin aanpassen in 3.1.10 geographical coverage

### ISSUE THREAD

**Issue by jambelien** [Geonovum/DCAT-AP-NL30#131]
Paragraaf: 3.1.10 geographical coverage
Type issue: redactioneel
Korte omschrijving van het probleem: zin aanpassen
Prioriteit issue:  Should-Have
Voorgestelde aanpassing:
- oorspronkelijke zin: Voor de bounding box (Bbox) zijn de coördinaten zijn de meest westelijke, oostelijke, noordelijke en zuidelijke coördinaat uit de horizontale dekking van de dataset weergegeven in latitude en longitude in decimale graden (noord en oost als positieve waarden).
- aanpassen naar: Voor de bounding box (Bbox) zijn als coördinaten de meest westelijke, oostelijke, noordelijke en zuidelijke coördinaat uit de horizontale dekking van de dataset weergegeven in latitude en longitude in decimale graden (noord en oost als positieve waarden).

**Comment by idevisser** [comment]
aangepast
