### ISSUE TITLE
Editorial: meermalig wordt catalog i.p.v. catalogus gebruikt

### ISSUE THREAD

**Issue by jambelien** [Geonovum/DCAT-AP-NL30#132]
Paragraaf: meerdere waaronder 3.1.13 identifier, 3.1.22 other identifier, 3.3.12 identifier, en 3.3.18 other identifier
Type issue: redactioneel
Korte omschrijving van het probleem: typo of onjuist vertaald
Prioriteit issue:   Should-Have
Voorgestelde aanpassing:
- overal het woord 'catalog' door 'catalogus' vervangen (gaat om de beschrijvende/inleidende teksten)

**Comment by skornsekj** [comment]
aangepast
