### ISSUE TITLE
Editorial: inleiding 3.2 Distribution; kleine tekstuele wijzigingen

### ISSUE THREAD

**Issue by jambelien** [Geonovum/DCAT-AP-NL30#133]
Paragraaf:3.2 Distribution - dcat:Distribution
Type issue: redactioneel
Korte omschrijving van het probleem: tekstuele aanpassingen
Prioriteit issue:  Should-Have
Voorgestelde aanpassing:
- de zin: 'Een distributie beschrijft hoe een (deel van) een dataset te verkrijgen is.' Aanpassen naar: 'Een distributie beschrijft hoe (een deel van) een dataset te verkrijgen is.'
- aan het einde van de zin: 'Een distributie levert rechtstreeks een dataset in een specifiek formaat op,' de komma vervangen door een punt: 'Een distributie levert rechtstreeks een dataset in een specifiek formaat op.'

**Comment by idevisser** [comment]
aangepast
