### ISSUE TITLE
Editorial: 3.2.2 access URL, kleine tekstuele aanpassing

### ISSUE THREAD

**Issue by jambelien** [Geonovum/DCAT-AP-NL30#134]
Paragraaf: 3.2.2 access URL
Type issue: redactioneel
Korte omschrijving van het probleem: extra punt verwijderen
Prioriteit issue:  Nice-to-Have
Voorgestelde aanpassing:
- de zin: 'De eigenschap access URL is verplicht in DCAT-AP, maar is niet altijd aanwezig, bijvoorbeeld als er alleen een rechtstreekse download link beschikbaar is, of alleen een access service of landingpage..' de dubbele punt vervangen door een enkele punt: 'De eigenschap access URL is verplicht in DCAT-AP, maar is niet altijd aanwezig, bijvoorbeeld als er alleen een rechtstreekse download link beschikbaar is, of alleen een access service of landingpage.'

**Comment by idevisser** [comment]
aangepast
