### ISSUE TITLE
Editorial: 3.2.3 applicable legislation, verwijzing bevat een spatie (%20) waardoor deze niet juist resolved

### ISSUE THREAD

**Issue by jambelien** [Geonovum/DCAT-AP-NL30#135]
Paragraaf:3.2.3 applicable legislation
Type issue: redactioneel
Korte omschrijving van het probleem: verwijzing resolved niet juist
Prioriteit issue:  Must-Have
Voorgestelde aanpassing:
- verwijzing: 'http://data.europa.eu/eli/reg_impl/2023/138/oj%20' vervangen door: 'http://data.europa.eu/eli/reg_impl/2023/138/oj'

**Comment by idevisser** [comment]
aangepast
