### ISSUE TITLE
Inhoudelijk: 3.2.13 language, property language gebruikt waarde lijst met 3-lettercodes (versus zie issue 85 door ons gekozen 2-lettercode voor taal)

### ISSUE THREAD

**Issue by jambelien** [Geonovum/DCAT-AP-NL30#136]
Paragraaf: 3.2.13 language, property language, keuze uit waardelijst: http://publications.europa.eu/resource/authority/language
Type issue: Inhoudelijk
Korte omschrijving van het probleem: deze keuze lijst is een 3-lettercode, terwijl eerder (zie issue 85) wij voor 2-lettercode hebben gekozen. Gelijk trekken (dus ook wij naar 3-lettercode en dus issue 85 weer openen)
Prioriteit issue:  Must-Have
Voorgestelde aanpassing: zie korte omschrijving.

**Comment by idevisser** [comment]
Ik ben met je eens dat het inconsistent is, maar je ziet in de language tags, waar issue 85 over gaat eigenlijk overal de twee letter code terug komen. Zelfs bij https://op.europa.eu/en/web/eu-vocabularies/concept/-/resource?uri=http://publications.europa.eu/resource/authority/language/NLD.
Lijkt me handiger het te laten zoals het is.
