### ISSUE TITLE
Editorial: 3.2.20 rights, in tekst GDA voorzien van link

### ISSUE THREAD

**Issue by jambelien** [Geonovum/DCAT-AP-NL30#137]
Paragraaf: 3.2.20 rights
Type issue: redactioneel
Korte omschrijving van het probleem: GDA is in dit stukje tekst niet van link voorzien (elders wel).
Prioriteit issue:  Should-Have
Voorgestelde aanpassing:
- zin: 'Deze eigenschap is verplicht, als de dataset onder de Data Governance Act (DGA) valt.' vervangen door: 'Deze eigenschap is verplicht, als de dataset onder de Data Governance Act ([DGA](https://digital-strategy.ec.europa.eu/en/policies/data-governance-act-explained)) valt.'

**Comment by idevisser** [comment]
aangepast
