### ISSUE TITLE
Editorial: toevoegen link naar "meertaligheid" bij alle "description" eigenschappen

### ISSUE THREAD

**Issue by jambelien** [Geonovum/DCAT-AP-NL30#14]
In paragraaf https://docs.geostandaarden.nl/dcat/dcat-ap-nl30/#description (3.1.7 description) wordt aan het einde beschreven: "Zie meertaligheid voor het omgaan met verschillende talen." 
Voorgestelde aanpassing: geef deze zin een "link" naar https://docs.geostandaarden.nl/dcat/dcat-ap-nl30/#10B7B8F1
en pas deze wijziging toe bij alle andere "description" eigenschappen als 3.2.8 description, 3.3.6 description etc.
prioriteit issue: Nice to have

**Comment by RemieJanssen** [comment]
Misschien breder trekken, en zo'n verwijzing toevoegen voor alle eigenschappen met een textuele Literal range (title, keyword, etc.)

**Comment by idevisser** [comment]
in ieder geval naar titel, description en version notes, in alle klassen. Daar is wel een verwijzing, maar is geen link

**Comment by idevisser** [comment]
aangepast
