### ISSUE TITLE
Missende properties in draft versie DCAT-AP SHACL

### ISSUE THREAD

**Issue by skornsekj** [Geonovum/DCAT-AP-NL30#142]
Paragraaf: meerdere

Type: Editoriaal

Omschrijving: In de meest recente werkversie van DCAT-AP-NL hebben we de meest recente draft versie van DCAT-AP SHACL gebruikt, om de tabellen te genereren. Daarin zijn een aantal eerder tekortkomingen opgelost, en daardoor ook een aantal issues in het Respect document DCAT-AP-NL. Na een check blijken er echter nog een aantal properties te missen in de [draft DCAT-AP SHACL](https://github.com/SEMICeu/DCAT-AP/blob/gh-pages/releases/3.0.0-draft/shacl/dcat-ap-SHACL.ttl). Deze missen daardoor nu ook in DCAT-AP-NL. 
Het betreft volgende properties: 

    Dataset: keyword
    Dataset: version notes
    Distribution + CatalogRecord: description
    Distribution + CatalogRecord:: title

Prioriteit:
must-have

Hiervoor is een [issue](https://github.com/SEMICeu/DCAT-AP/issues/379) aangemaakt bij DCAT-AP

**Comment by idevisser** [comment]
nog checken of de tekstuele aanpassingen bij description etc. bij missende elementen is doorgevoerd

**Comment by skornsekj** [comment]
Deze bevinding is inmiddels opgepakt door DCAT-AP en word verwerkt in de volgende versie van de SHACL.

**Comment by idevisser** [comment]
update tekst meertaligheid op deze missende elementen is doorgevoerd
