### ISSUE TITLE
Inhoudelijk. Uitgangspunten. Onvoldoende onderbouwing NL profiel

### ISSUE THREAD

**Issue by skornsekj** [Geonovum/DCAT-AP-NL30#144]
Naam inbrenger: Remie Janssen
Paragraaf: Uitgangspunten
Type issue:  Inhoudelijk
Korte omschrijving van het issue: 
De noodzaak van een Nederlands applicatieprofiel is misschien onvoldoende onderbouwd. De vertaling is uiteraard noodzakelijk voor eenheid van taal bij het Nederlandse gebruik van de DCAT standaard. Voor de (kleine hoeveelheid) noodzakelijke aanpassingen voor Nederlandse toepassing is het misschien gepaster om twee aparte documenten te maken: 1 voor de Nederlandse vertaling van het Europese DCAT-AP, en een andere voor wat Nederlandse aanvullingen. Die aanvullingen moeten ook strict noodzakelijk zijn om aan Nederlandse wetgeving te voldoen.
Prioriteit issue: Must-Have
Voorgestelde aanpassing: 
Dit document in twee opslitsen: 1 voor de vertaling van DCAT-AP, en 1 voor de Nederlandse specificatie. Dat tweede deel moet tot doel hebben een MINIMAAL aantal aanpassingen te hebben t.o.v. DCAT-AP, ten behoeve van het gebruik van de Europese standaard. Afwijkingen moeten onderbouwd worden met wetgeving.

**Comment by idevisser** [comment]
Het is bij het opstellen van dit profiel geen uitgangspunt geweest dat afwijkingen t.o.v DCAT-AP onderbouwd moeten worden met wetgeving.
