### ISSUE TITLE
Inhoudelijk. License niet alleen beperken tot CC

### ISSUE THREAD

**Issue by skornsekj** [Geonovum/DCAT-AP-NL30#147]
Naam inbrenger: Andres Ramos 

Paragraaf: 3.2.14 license

Type issue: Inhoudelijk

Korte omschrijving van het issue:
Volgens de text Creative Commons Licenties (CC) is vereist, maar volgens de Interoperable Europe Act (regel 36) "De portaalsites van de lidstaten die opensourceoplossingen verzamelen die gekoppeld zijn aan het Interoperabel Europa-portaal, moeten het gebruik van de EUPL mogelijk maken, zonder de mogelijkheid uit te sluiten dat dergelijke portalen het gebruik van andere opensourcelicenties kunnen toestaan." Zie ook https://joinup.ec.europa.eu/collection/eupl/news/eupl-interoperable-europe-act

Prioriteit issue: Should-have

Voorgestelde aanpassing: 
Niet alleen de CC vereisten maar wel aanbevelen. Voor de waardelijst is genoeg als de  [Niet allen de CC vereisten maar wel aanbevelen. Voor de waardelijst is genoeg als de SPDX wordt gebruik [https://spdx.org/licenses/](https://spdx.org/licenses/)

**Comment by idevisser** [comment]
EUPL is voor software, niet voor data, zie  https://nl.wikipedia.org/wiki/Openbare_Licentie_van_de_Europese_Unie
