### ISSUE TITLE
Editorial. Uitgangspunten Open Data vs AccessRights

### ISSUE THREAD

**Issue by skornsekj** [Geonovum/DCAT-AP-NL30#148]
Naam inbrenger: Andre van Brussel (ICTU - Federaal Datastelsel)

Paragraaf: Uitgangspunten 

Type issue: Editorial

Korte omschrijving van het issue:
Het gekozen uitgangspunt is primair open data maar wordt hier niet toe beperkt. Dat verhoudt zich moeilijk tot het attribuut AccesRights welke verplicht is en waar Open Data 1 van de 3 mogelijke waarden is

Prioriteit issue: 

Voorgestelde aanpassing:

**Comment by skornsekj** [comment]
Aanvulling inbrenger. 

Voorstel: uitgangspunt Open Data weghalen. Wordt namelijk niet duidelijk wat dat uitgangspunt dan voor gevolgen heeft voor de verdere gemaakte ontwerp keuzes.

Of veranderen in iets als: de ervaringen met het beschrijven van datasets zijn vooral afkomstig uit de Open Data wereld maar de DCAT standaard is ook geschikt voor het vindbaar maken van data waaraan toegangsbeperkingen zitten (bijv intelectueel eigendomsrecht, auteursrecht) of gesloten is (bijv. Persoonsgegevens). 

Dan sluit het beter aan op de feitelijk waardelijst van het kenmerk Access Rights 
_Acces Rights: Deze eigenschap bevat informatie die aangeeft of de dataset openbaar toegankelijk is, toegangsbeperkingen heeft of niet openbaar is._

**Comment by idevisser** [comment]
aangepast
