### ISSUE TITLE
Inhoudelijk. Creator / Publisher mapping naar andere waardelijsten?

### ISSUE THREAD

**Issue by skornsekj** [Geonovum/DCAT-AP-NL30#149]
Naam inbrenger: Andre van Brussel (ICTU - Federaal Datastelsel)

Paragraaf: 3.1.5. Creator

Type issue: Inhoudelijk

Korte omschrijving van het issue:
Voor de organisatie (creator of publisher) worden waardelijsten uit het Register van Overheidsorganisaties of de EU Core Busniess Organisations voorgesteld. Is er ook nagedacht over mappings naar bestaande organisatie-identiteiten zoals nummer uit het Handelsregister, en het OIN? Geldt uiteraard ook voor de Creator of Publisher van een Dataservice

Prioriteit issue:

Voorgestelde aanpassing:

**Comment by copycatK** [comment]
In de kern is het probleem dat vrijwel iedere organisatie een rol zou kunnen spelen in het beschrijven van gegevens op DCAT. Voor zover ik weer is daar geen sluitende oplossing voor.
Mbt het beschrijven van organisatie zijn er op dit moment diverse bewegingen gaande. Het bovengenoemde register van Overheidsorganisatie van TOOI wordt veel gebruikt maar heeft duidelijk gedefinieerde beperkingen. TOOI is bezig meer organisatie te beschrijven, maar zal zich altijd beperken tot een vorm van overheidsorganisaties . 
Voor zover ik weet lopen er gesprekken mbt de relatie tussen de inhoud van het OIN register en dat van het Handelsregister. Daaraan zitten zoals ik het begrepen heb een aantal haken en ogen (bijv organisatie hebben meerdere OIN-nummers die niet te projecteren zijn op entiteiten van dezelfde organisatie in het HR) Ook is de inhoud en doel van beide registers niet gelijk. 
Mijn indruk is dat deze oplossingen op dit moment niet ontwikkeld genoeg zijn om in het profiel op te nemen en dat we dat dus op een toekomstig moment moeten doen.

**Comment by idevisser** [comment]
Dit is een correcte inschating. Daarnaast gaat deze werkgroep geen mappings tussen waardelijsten maken.
