### ISSUE TITLE
Editorial: datasetreeks paragraaf 3.1.14 in series

### ISSUE THREAD

**Issue by jambelien** [Geonovum/DCAT-AP-NL30#15]
In paragraaf https://docs.geostandaarden.nl/dcat/dcat-ap-nl30/#in-series (3.1.14 in series) wordt voor het eerst (en zover ik nu kan achterhalen) de term "datasetreeks" gebruikt. Tot nu toe wordt elders in documentatie DatasetSeries gebruikt.
Voorgestelde aanpassing: 
- of term "datasetreeks" opnemen in bij de beschrijving van "dataset serie" in https://docs.geostandaarden.nl/dcat/dcat-ap-nl30/#7001826E (1. Termen en definities). Bijvoorbeeld "Een dataset serie (andere term hiervoor: datasetreeks ) is een verzameling van datasets met dezelfde productspecificaties. Productspecificaties zijn thema, resolutie en methodologie."
- of datasetreeks vervangen door "dataset serie". de zin bij 3.1.14 zou dan worden -> "Een dataset serie waarvan de dataset deel uitmaakt."
Prioriteit issue: nice to have

**Comment by skornsekj** [comment]
Voorstel: datasetreeks vervangen door "dataset serie" in de par 3.1.14. 

Is verwerkt.
