### ISSUE TITLE
Editorial. Theme - domein specifieke vocabularies

### ISSUE THREAD

**Issue by skornsekj** [Geonovum/DCAT-AP-NL30#150]
Naam inbrenger: Andre van Brussel (ICTU - Federaal Datastelsel)

Paragraaf: 3.3.22 Theme

Type issue: Editorial

Korte omschrijving van het issue:
Naast een verplicht EU thema wordt ook aanbevolen om thema's uit domeinspecifieke vocabularties op te nemen. Dat wordt verder niet uitgelegd. Daarnaast wordt ook niet uitgelegd wat er gebeurt met de huidige thema's zoals gebruikt door data.overheid.nl. Expliciet uitfaseren? 

Prioriteit issue:

Voorgestelde aanpassing:

**Comment by copycatK** [comment]
Met themas moeten we praktisch omgaan. Zoals al eerder besproken bestaan er drie soorten:
1. Themalijsten die voor alle datasets kunnen gelden, zoals TOP-lijst of Stelselcatalogus clusterbegrippen
2. Themalijsten die op een bepaald terrein veel waarde hebben, maar daarbuiten niet, zgn domeinspecifieke lijsten. Voorbeelden te over: Lijsten in het medisch domein, voor GEO-toepassingen, onderwijs, energietransitie, etc. Kenmerk van deze lijsten is dat alleen datasets uit dat specifieke domein deze lijsten zinnig kunnen invullen, terwijl ze binnen dat domein veel waarde hebben
3. Themalijsten die voor een kleine groep/toepassing nuttig zijn. Bijvoorbeeld om een grote hoeveelheid gelijksoortige data mee te kunnen annoteren zodat eenvoudig onderscheid gemaakt kan worden

Het lijkt mij dat themalijsten van categorie 1 en 2 beheer nodig hebben. De lijsten moeten worden beheerd en uiteindelijk moeten er een aantal worden voorgeschreven dan wel aangeboden voor partijen die DCAT beschrijvingen opstellen.
Omdat er op dit moment nog weinig consensus bestaat over deze lijsten en er bovendien gebrek is aan adequaat beheerde lijsten, lijkt dit me iets om met de community door te ontwikkelen.
Aangezien thema-lijsten begrippenkaders zijn, zal een succesvol gebruik van de nieuwe NL-SBB standaard het ontwikkelen van themalijsten kunnen bevorderen.
Als er themalijsten zijn die op dit moment al zo belangrijke worden gevonden dat ze op dit moment al in het profiel moeten worden opgenomen, dan zouden we die moeten beoordelen als werkgroep. 
Over de themalijst van DONL is volgens mij afgesproken dat er waarschijnlijk een mapping gemaakt kan worden van de huidige lijst naar de DCAT-AP lijst op het moment dat DONL de DCAT-AP-NL standaard gaat oversteunen. Die oplossing ligt bij DONL en niet in deze werkgroep.

**Comment by idevisser** [comment]
Europees gezien is hier nog een discussie over hoe domeinspecifieke vocabularties op te nemen. Zie issue https://github.com/Geonovum/DCAT-AP-NL30/issues/69 Als dat duidelijk is, gaan we de tekst aanpassen.

Wat hierboven terecht wordt gezegd is dat deze werkgroep geen mappings maakt op de themalijst van DONL, dat is aan DONL om dat op te pakken.
