### ISSUE TITLE
Editorial: dode link naar DCAT-AP-3.0

### ISSUE THREAD

**Issue by hoverbee** [Geonovum/DCAT-AP-NL30#18]
In C.1 Normatieve referenties staat

[DCAT-AP-3.0]
[DCAT-AP-3.0](https://semiceu.github.io//DCAT-AP/releases/3.0). Bert Van Nuffelen. 2024-02-12. Candidate Recommendation. URL: https://semiceu.github.io//DCAT-AP/releases/3.0

De links geven 404.
De juiste link is https://semiceu.github.io/DCAT-AP/releases/3.0.0/?

**Comment by skornsekj** [comment]
verwerkt
