### ISSUE TITLE
Editorial: De DCAT-AP-URI's resolven niet 

### ISSUE THREAD

**Issue by hoverbee** [Geonovum/DCAT-AP-NL30#19]
De URI's van de DCAT-AP-termen resolven niet. Is het misschien handiger om in plaats van de URI's de URL's van de properties in het DCAT-AP-document op te nemen? Bijvoorbeeld https://semiceu.github.io/DCAT-AP/releases/3.0.0/#Dataset.applicablelegislation

**Comment by skornsekj** [comment]
Opgelost.
