### ISSUE TITLE
normatieve referentie

### ISSUE THREAD

**Issue by idevisser** [Geonovum/DCAT-AP-NL30#191]
[DCAT-AP-3.0]
[DCAT-AP-3.0](https://semiceu.github.io/DCAT-AP/releases/3.0.0/). SEMIC. 12 February 2024. Candidate Recommendation. URL: https://semiceu.github.io/DCAT-AP/releases/3.0.0/

aanpassen naar 14 June 2024 en status naar recommendation

**Comment by NielsHoffmann** [comment]
aangepast. dcat-3.0 ook aangepast naar recommendation 22 augustus 2024
