### ISSUE TITLE
Inhoudelijk en editorial: vergelijking tussen DCAT-AP-EU en DCAT-AP-NL

### ISSUE THREAD

**Issue by hoverbee** [Geonovum/DCAT-AP-NL30#20]
Voor een efficiënte beoordeling van het werk van de werkgroep DCAT-AP-NL zou het helpen als er een overzicht is van de punten waarop DCAT-AP-NL afwijkt van DCAT-AP-EU en als bij elke afwijking de rationale wordt gegeven.

**Comment by CorMelse** [comment]
Eens met @hoverbee

**Comment by RemieJanssen** [comment]
+1

Idealiter zou ik het ook op twee plekken zien:
 - Op lokatie in het document waar afgeweken wordt
 - In een overzicht (tabel?) van alle afwijkingen

**Comment by idevisser** [comment]
Voor overzicht van afwijkingen hebben we in de werkgroep een tabel bijgehouden. Deze heeft als basis gediend voor dit profiel.
We onderzoeken wat mogelijk is om in het profiel  te duiden waar afwijkingen zitten.

**Comment by skornsekj** [comment]
Voorstel: In de overzichtstabellen per klasse wordt een kolom toegevoegd. Daarin wordt aangegeven of betreffende eigenschap 1-op-1 is overgenomen uit DCAT-AP of dat de property daarvan afwijkt in DCAT-AP-NL. In een apart document (github) wordt een beknopt overzicht gegeven wat de verschillen zijn.

**Comment by skornsekj** [comment]
aangepast

**Comment by hoverbee** [comment]
De noot in sectie 2.5 komt wat laat aan de orde,
Een overzicht met de verschillen tussen DCAT-AP-NL en DCAT-AP vind je in het document ['Verschillen DCAT-AP en DCAT-AP-NL.pdf'](https://github.com/Geonovum/DCAT-AP-NL30)
 
De legenda bij dat overzicht ontbreekt helaas. Ik hoop dat ik de afko's zo goed heb geïnterpreteerd (in ieder geval de "R" niet):
 
AP = DCAT-AP = EU Application-profile op DCAT 3.0
HVD = High-value-dataset (Zie [Digital Health EU](https://digitalhealtheurope.eu/glossary/high-value-dataset/#:~:text=From%20the%20publisher's%20perspective%2C%20a,it%20brings%20value%20to%20a) en [DONL](https://data.overheid.nl/high-value-datasets))
 
V = Verplicht
C = Conditioneel verplicht
A = Aanbevolen


O = Optioneel
**R = mij een Raadsel** Recommended? Maar da's Engels.
