### ISSUE TITLE
Editorial: leesbaarheid figuur 1

### ISSUE THREAD

**Issue by vanmeule** [Geonovum/DCAT-AP-NL30#21]
- Paragraaf: Inleiding, naam klasse: n. v. t, naam property: n. v. t. 
- Type issue: Editorial
- Korte omschrijving van het issue / probleem: figuur 1 is erg lastig te lezen door de gebruikte kleuren, met name het groen/geel van bijvoorbeeld het DCAT-AP-DONL 2.0 blokje, de legenda daarvan kan ik niet lezen. Verklaring van het oranje DCAT-AP-NL ontbreekt. 
- Prioriteit issue: Nice-to-Have
- Voorgestelde aanpassing: andere kleurenvoor blokjes, of donkere letters. Toevoegen verklaring oranje blokje. Typefout in blauwe blokje (die kan ik wel lezen): extention moet extension zijn.

**Comment by idevisser** [comment]
aangepast
