### ISSUE TITLE
Editorial: niet lopende zin

### ISSUE THREAD

**Issue by vanmeule** [Geonovum/DCAT-AP-NL30#22]
- Paragraaf: 2.1, naam klasse: n. v. t, naam property: n. v. t. 
- Type issue: Editorial
- Korte omschrijving van het issue / probleem: zin loopt niet
- Prioriteit issue: Nice-to-Have
- Voorgestelde aanpassing: "bij W3C" in de zin "Het toepassingsprofiel in dit document is gebaseerd op de specificatie van de Data Catalog Vocabulary (DCAT), ontwikkeld onder verantwoordelijkheid van de Government Linked Data Working Group bij W3C." vervangen door "van W3C"

**Comment by skornsekj** [comment]
verwerkt
