### ISSUE TITLE
Editorial: d/t/ foutje

### ISSUE THREAD

**Issue by vanmeule** [Geonovum/DCAT-AP-NL30#23]
- Paragraaf: 2.6, naam klasse: n. v. t, naam property: n. v. t. 
- Type issue: Editorial
- Korte omschrijving van het issue / probleem: d/t fout
- Prioriteit issue: Nice-to-Have
- Voorgestelde aanpassing: "herhaalt" in "Voor elke vertaling wordt de eigenschap herhaalt met de toevoeging van een language tag om aan te geven in welke taal de waarde geschreven is." moet "herhaald" zijn

**Comment by skornsekj** [comment]
verwerkt.
