### ISSUE TITLE
Inhoudelijk: codelijsten geographical coverage

### ISSUE THREAD

**Issue by vanmeule** [Geonovum/DCAT-AP-NL30#24]
- Paragraaf: 3.1.10, naam klasse: Dataset, naam property: geographical coverage 
- Type issue: Inhoudelijk
- Korte omschrijving van het issue / probleem: Verschillemde codelijsten, https://vocabs.cbs.nl/nl/ en GeoNames in de eerste zin, http://publications.europa.eu/resource/authority/continent/, http://publications.europa.eu/resource/authority/country, http://publications.europa.eu/resource/authority/place/, http://sws.geonames.org/ in de de tweede zin
- Prioriteit issue: Should-have
- Voorgestelde aanpassing: Zin "Gebruik hiervoor een waarde uit EU Vocabularies Continents Named Authority List, EU Vocabularies Countries Named Authority List, EU Vocabularies Places Named Authority List, Geonames" weghalen. GeoNames.org in eerste zin hyperlink maken.

**Comment by CorMelse** [comment]
@vanmeule, komt ook voor in §3.4.7. Catalog-geographical coverage.
ook hier dezelfde aanpassing doorvoeren? 
Zou ik voor zijn.

**Comment by idevisser** [comment]
nog even goed checken wat verplicht is en wat de opties zijn

**Comment by idevisser** [comment]
aangepast
