### ISSUE TITLE
Editorial: afkorting CC verklaren

### ISSUE THREAD

**Issue by vanmeule** [Geonovum/DCAT-AP-NL30#26]
- Paragraaf: 3.2.14, naam klasse: Distribution, naam property: licence 
- Type issue: Editorial
- Korte omschrijving van het issue / probleem: Afkorting CC wordt gebruikt zonder aan te geven wat hij betekent 
- Prioriteit issue: Nice-to-Have
- Voorgestelde aanpassing: Tussen haajkes de afkorting (CC) toevoegen in de zin "Gebruik van Creative Commons Licenties is vereist. Aanbevolen wordt om steeds de meest recente versie van een licentie te gebruiken.": "Gebruik van Creative Commons **(CC)** Licenties is vereist. Aanbevolen wordt om steeds de meest recente versie van een licentie te gebruiken."

**Comment by skornsekj** [comment]
verwerkt.
