### ISSUE TITLE
Editoriaal: eush prefix

### ISSUE THREAD

**Issue by Bakkej** [Geonovum/DCAT-AP-NL30#27]
**Paragraaf**:
**Type**: 
Editoriaal
**Omschrijving**:
In de DCAT-AP-NL shapes wordt in plaats van `sh:message`, `eush:message` gebruikt. 
Waarom wordt er afgeweken van sh:message? 
eush ( `https://purl.eu/ns/shacl#`) resolved overigens niet.
**Prioriteit**:
should-have

**Comment by pmaria** [comment]
@Bakkej 

Diezelfde vraag had ik ook toen ik naar de shapes van DCAT-AP keek. Zie issue https://github.com/SEMICeu/DCAT-AP/issues/355 voor uitleg.

Er is gekozen om `eush:message` te hanteren, in navolging van DCAT-AP, zodat de validatie via de Validator testbed instance https://www.itb.ec.europa.eu/shacl/any/upload op dezelfde manier werkt als voor DCAT-AP.
