### ISSUE TITLE
Editorial: Afkorting DGA

### ISSUE THREAD

**Issue by aframosp** [Geonovum/DCAT-AP-NL30#28]
Paragraaf: 3.2.5 (3.2.11), naam klasse: Distribution, naam property: bytesize (format)
Type issue: Editorial
Korte omschrijving van het issue / probleem: Afkorting DGA wordt gebruikt zonder context
Prioriteit issue: Nice-to-Have
Voorgestelde aanpassing: "Deze eigenschap is verplicht, als de dataset onder de Europese Data Governance Act (DGA) uitvoeringsverordening valt." Misschien met de [link](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32022R0868) naar de verordening.

**Comment by idevisser** [comment]
zie https://github.com/Geonovum/DCAT-AP-NL30/issues/44

aangepast
