### ISSUE TITLE
Editorial: niet werkende links in property 'applicable legislation' van meerdere klassen (3.1.2, 3.2.3, 3.3.2)

### ISSUE THREAD

**Issue by HNeikes** [Geonovum/DCAT-AP-NL30#29]
In de paragrafen van property 'applicable legislation' van meerdere klassen (3.1.2, 3.2.3, 3.3.2), werken meerdere links niet:

[http://data.europa.eu/eli/reg_impl/2023/138/oj](http://data.europa.eu/eli/reg_impl/2023/138/oj%20) (er lijkt een spatie achter te zitten)

Daarnaast blokkeert de browser bij het openen van [eli:LegalResource](http://data.europa.eu/eli/ontology#LegalResource) een onveilige download:
<img width="1000" alt="Screenshot 2024-03-19 at 19 36 41" src="https://github.com/Geonovum/DCAT-AP-NL30/assets/50417877/74007eb3-d259-43f7-85ba-4096bd0453fa">

Voorgestelde wijziging: de links corrigeren.
Prioriteit: nice-to-have

**Comment by CorMelse** [comment]
@HNeikes: _"Daarnaast blokkeert de browser bij het openen van [eli:LegalResource](http://data.europa.eu/eli/ontology#LegalResource) een onveilige download:"_

ik gebruik FF en daar wordt een RDF document geopend, is wel leesbaar maar niet echt gebruikersvriendelijk. beter een humanreadable pagina linken ;-)

**Comment by skornsekj** [comment]
Gerelateerde issue #63 blijft open. Dit issue wordt gesloten.
