### ISSUE TITLE
Editorial; optionaliteit toevoegen aan de beschrijvingen van de properties 

### ISSUE THREAD

**Issue by HNeikes** [Geonovum/DCAT-AP-NL30#30]
Aan het begin van de beschrijving van elke klasse staat een tabel met alle properties (per rij) met vijf kolommen.
Daaronder volgt voor elke property een gedetailleerde beschrijving, met daarbij per property weer een tabel (zie voorbeeld hieronder), waarin de informatie van bovenstaande tabel per eigenschap herhaald worden, behalve de optionaliteit.
Is er een specifieke reden dat de optionaliteit hier niet nog een keer genoemd wordt?
Zo niet, voorgestelde wijziging: de optionaliteit ook toevoegen aan de beschrijvingen van de properties.

Prioriteit: nice-to-have

![Schermafbeelding 2024-03-20 091915](https://github.com/Geonovum/DCAT-AP-NL30/assets/50417877/c6da3b73-5e63-48ec-baf0-b7be76eb8444)

**Comment by CorMelse** [comment]
eens met @HNeikes, werk beter voor de leesbaarheid. hoef je niet steeds terug naar de tabel

**Comment by skornsekj** [comment]
Aangepast.
