### ISSUE TITLE
Editorial: DataService-contactpoint (3.3.4)

### ISSUE THREAD

**Issue by CorMelse** [Geonovum/DCAT-AP-NL30#32]
o	Paragraaf, naam klasse, naam property: 
§3.3.4, DataService, contact point 

o	Type issue: Inhoudelijk of editorial 
Editorial

o	Korte omschrijving van het issue / probleem
property wijkt af van dezelfde property in DataSet (§3.1.4) & Catalog (§3.4.3) & DatasetSeries (§3.6.2)
mist Range: vcard:Kind

o	Prioriteit issue:  Must-Have, Should-Have, Nice-to-Have
Must have (i.m.h.o.)

o	Voorgestelde aanpassing
toevoegen in §3.3.4

**Comment by skornsekj** [comment]
is aangepast
