### ISSUE TITLE
Validatie beschikbaar?

### ISSUE THREAD

**Issue by ticheler** [Geonovum/DCAT-AP-NL30#34]
Hallo @idevisser, @pmaria,
Wordt er al gewerkt aan een validator op basis van SHACL shapes voor dit profiel? Is er misschien al een eerste opzet beschikbaar? En indien dat niet het geval is, zijn er concrete plannen om dit te realiseren? Het hoofdstuk validatie is vooralsnog leeg, vandaar deze vraag.
Bij voorbaat dank. Met vriendelijke groet,
Jeroen

**Comment by idevisser** [comment]
Validatie  met de NL SHACL shapes kan worden uitgevoerd met de generieke EU validator. Hoe, wordt in het hoofdstuk validatie uitgelegd, die beschikbaar komt in de versie voor consultatie.
