### ISSUE TITLE
Meer dan een dct:title mogelijk?

### ISSUE THREAD

**Issue by hekl** [Geonovum/DCAT-AP-NL30#35]
3.1.37 title
Type issue: inhoudelijk
Omschrijving: hier staat: Cardinality 1..n. 
Ik ben geen voorstander van meer dan één titel. Een alternatieve titel is goed, maar dan met een eigen property. 
Prioriteit: Must-Have
Voorgestelde aanpassing:

- Cardinality  1..1

- Alternatieve titel dct:alternative Optional, Cardinality  1..n

**Comment by RemieJanssen** [comment]
Ik ben het ermee eens dat er per taal maar een titel zou moeten zijn. Maar om meertaligheid te ondersteunen moet je per taal een title toe kunnen voegen. Het lijkt mij onwenselijk dat die in een alternatieve property terecht komen.

**Comment by hekl** [comment]
Natuurlijk, dat klopt. Ik interpreteer de meertaligheid niet als meer dan één titel. Het punt is dat je eigenlijk moet aangeven dat meerdere titels alleen meertalige titels kunnen zijn.

**Comment by idevisser** [comment]
Zie issue #39 bij de properties wordt duidelijk gespecificeerd dat per taal maar 1 titel (of andere propertie) kan worden opgenomen.

**Comment by idevisser** [comment]
aangepast
