### ISSUE TITLE
Editorial: link naar Geonames.org

### ISSUE THREAD

**Issue by CorMelse** [Geonovum/DCAT-AP-NL30#36]
in de teksten wordt verwezen naar Geonames.org, maar de link komt op een niet goed werkende website uit: [https://sws.geonames.org](https://sws.geonames.org)
beter verwijzen naar de meer logische en wel werkende site [https://www.geonames.org](https://www.geonames.org)

daarnaast is sponoring door diverse casino's een bedenkelijke? maar buiten de invloed van de werkgroep vrees ik ;-)

**Comment by idevisser** [comment]
aangepast
