### ISSUE TITLE
Range van dataset dct:source

### ISSUE THREAD

**Issue by hekl** [Geonovum/DCAT-AP-NL30#37]
3.1.31 source
Type issue: Inhoudelijk 
Omschrijving: Er staat bij Dataset: **Range dcat:Dataset**. Waar is deze range op gebaseerd? Naar mijn idee kan de bron van een dataset ook iets anders zijn dan een dataset. 
Prioriteit issue:  Should-Have
Voorgestelde aanpassing; relax de Range , bijvoorbeeld door ook op te nemen: prov:Derivation of prov:PrimarySource .

**Comment by idevisser** [comment]
Het is gebaseerd is op de DCAT-AP, uitgangspunt is dat we conform DCAT-AP het NL profiel ontwikkelen, tenzij er specifieke toepassingen zijn die dat rechtvaardigen.

**Comment by idevisser** [comment]
voorstel om DCAT-AP te volgen en het te laten zoals het nu in het profiel is opgenomen
