### ISSUE TITLE
Onduidelijkheid in omgang met meertaligheid bij 1..n eigenschappen

### ISSUE THREAD

**Issue by RemieJanssen** [Geonovum/DCAT-AP-NL30#39]
Voor textuele eigenschappen met een 1..n kardinaliteit is het onduidelijk hoe omgegaan moet worden met meertaligheid.

In het document staat nu in '2.6 Ondersteuning voor meertaligheid'
> Elke taal mag slechts één keer voorkomen. 
Dat leidt tot de situatie waarin de volgende dataset ongeldig is vanwege het meervoudig voorkomen van een Nederlandstalig keyword:
```
_ a dcat:Dataset ;
  dcat:keyword "infectieziekte"@nl ;
  dcat:keyword "vaccin"@nl ;
  dcat:keyword "volksgezondheid"@nl .
```

**Comment by idevisser** [comment]
aangepast bij  ondersteuning meertaligheid en het bij de de eigenschappen specifiek benoemt
