### ISSUE TITLE
Meertaligheid in Ondersteunende Klassen

### ISSUE THREAD

**Issue by RemieJanssen** [Geonovum/DCAT-AP-NL30#40]
2.6 Ondersteuning voor meertaligheid 

Het is niet duidelijk hoe om moet worden gegaan met meertaligheid van velden in Ondersteunende Klassen (zoals genoemd in 4. Ondersteunende Klassen).

Voorstel voor verduidelijking:
> Maak bij het gebruik van ondersteunde klassen **niet** een object per taal aan. Maak in plaats daarvan één object aan en gebruik in de eigenschappen daarvan meertalige eigenschappen zoals beschreven voor de eigenschappen `dcat:title` en `dcat:description` hierboven.

**Comment by idevisser** [comment]
voorstel tot aanpassing;

Gebruik voor meertaligheid van eigenschappen in de Ondersteunende Klassen zoals beschreven voor de eigenschappen dcat:title en dcat:description hierboven.

**Comment by idevisser** [comment]
Is er een reden dat er in de ondersteunende klassen op een andere manier met meertaligheid om moet worden gegaan?

**Comment by RemieJanssen** [comment]
Ik zou het juist op dezelfde manier doen als in de DCAT klasses. Het kan echter zijn dat er onduidelijkheid is over hoe dat gedaan zou moeten worden. Er zijn meerdere mogelijkheden om meertaligheid voor elkaar te krijgen bij properties die ondersteunende klassen gebruiken. Je kan:
1.  je kan voor iedere taal een object in de ondersteunende klasse maken
2. je kan het object in de ondersteunende klasse meertalig maken
De tweede optie lijkt me beter, maar ik ben in discussies over metadatarecords ook wel suggesties tegengekomen voor iets wat op de eerste optie lijkt. 

Dat komt bijvoorbeeld terug in de (misschien outdated?) DONL AP, waarin donl:metadatalanguage gebruikt wordt om de taal van het record vast te leggen. In plaats van een meertalig record, wordt dan een record per taal gemaakt.

In dit geval zou je het bijvoorbeeld voor contactPoint als volgt kunnen zien. Stel dat er een Dataset is met een contactpunt genaamd "Voorbeeld". De eerste optie hierboven zou dan leiden tot het toevoegen van twee contactPoint objecten aan de dataset:
``` turtle
my_dataset dcat:contactPoint _:b1 .
_:b1 a vcard:Group;
    vcard:fn "Voorbeeld"@nl .
my_dataset dcat:contactPoint _:b2 .
_:b2 a vcard:Group;
    vcard:fn "Example"@en .
```
de tweede optie geeft een contactPoint object met een meertalig gedefinieerde naam:
``` turtle
my_dataset dcat:contactPoint _:b1 .
_:b1 a vcard:Group;
    vcard:fn "Voorbeeld"@nl .
    vcard:fn "Example"@en .
```

**Comment by idevisser** [comment]
aangepast
