### ISSUE TITLE
Editorial: Voeg referentie HVD toe in Samenvatting

### ISSUE THREAD

**Issue by RemieJanssen** [Geonovum/DCAT-AP-NL30#41]
Samenvatting

In de samenvatting staat een verwijzing naar de 'DCAT-AP for High Value Datasets'. Later in het document wordt daar ook een referentie voor gegeven [DCAT-AP-HVD]. 

Voorgestelde aanpassing:
Voeg die referentie ook toe in de samenvatting.

**Comment by skornsekj** [comment]
verwerkt.
