### ISSUE TITLE
Editorial: Referenties naar BCP 14

### ISSUE THREAD

**Issue by RemieJanssen** [Geonovum/DCAT-AP-NL30#42]
Conformiteit

In het hoodstuk 'Conformiteit' wordt verwezen naar BCP 14 voor de betekenis van MUST etc. Echter beschrijft dit document slechts de Engelse termen, terwijl verwezen wordt om de Nederlandse termen te verklaren. Graag dit correct doen, en een vertaling van de termen geven.

Daarnaast kan gelijk de referentie mooier gemaakt worden. Het lijkt mij voldoende om alleen naar BCP14 te verwijzen, en niet ook naar RFC8174 en RFC2119. Mocht er toch voor worden gekozen om alledrie de referenties te behouden, dan dient de link voor [RFC8174] aangepast te worden, zodat hij niet langer naar https://www.rfc-editor.org/rfc/rfc5646 verwijst, maar naar https://www.rfc-editor.org/rfc/rfc8174.

**Comment by skornsekj** [comment]
Voorstel. De termen MOET (MUST), BEHOORT (SHOULD) en MAG (MAY) in dit document moeten worden geïnterpreteerd als in [BCP 14](https://www.rfc-editor.org/info/bcp14) en alleen als deze in hoofdletters zijn weergegeven, zoals hier getoond. 

Is verwerkt.
