### ISSUE TITLE
Editorial: Gebruik van afkortingen in het algemeen en specifiek voorbeeld DGA

### ISSUE THREAD

**Issue by jambelien** [Geonovum/DCAT-AP-NL30#44]
Paragraaf 3.2.5 byte size
Issue: editorial
Korte omschrijving: in deze paragraaf wordt voor het eerst de afkorting DGA gebruikt. 
Voorstel aanpassing: elke afkorting te voorzien van een volledig uitgeschreven versie. Dus in dit geval DGA: Data Governance Act (DGA). Indien er een referentie is deze dan toe te voegen: bijvoorbeeld voor DGA https://digital-strategy.ec.europa.eu/en/policies/data-governance-act-explained . 
Andere optie zou zijn om onder termen en definities de veel gebruikte afkortingen op te nemen.
Priority: should have

**Comment by idevisser** [comment]
aangepast
