### ISSUE TITLE
Editorial: Figuur 2

### ISSUE THREAD

**Issue by RemieJanssen** [Geonovum/DCAT-AP-NL30#48]
Betreft: Figuur 2

Twee issues:
 - de dubbele punt (:) mist in `dcat:Distribution`
 - het is onduidelijk welke eigenschappen gekozen zijn om op te nemen. Voorstel: neem precies de verplichte eigenschappen van iedere klasse op in dit diagram.

**Comment by jambelien** [comment]
Nog niet expliciet als open issue opgenomen maar wel gerelateerd aan Figuur 2
Paragraaf: 2.2 Overzicht klassen, Figuur 2
Type issue: redactioneel & inhoudelijk
Korte omschrijving van het issue: 
1) Figuur legenda moet nog worden aangepast
2) Datasetseries nog niet toegevoegd
Prioriteit issue:  Must-Have
Voorgestelde aanpassing: het figuur onderschrift aanpassen en Figuur 2 inhoudelijk van klasse datasetseries voorzien

**Comment by idevisser** [comment]
aangpast
