### ISSUE TITLE
Inhoudelijk: Onduidelijkheid in optionaliteit verwerking gegevens

### ISSUE THREAD

**Issue by RemieJanssen** [Geonovum/DCAT-AP-NL30#49]
Betreft: 2.3 Optionaliteit
> In de gegeven context betekent de term "verwerken" dat ontvangers binnenkomende gegevens MOETEN accepteren en deze gegevens op transparante wijze aan applicaties en diensten moeten leveren. Het impliceert noch schrijft voor wat applicaties en diensten uiteindelijk met de gegevens doen (parseren, converteren, opslaan, doorzoekbaar maken, weergeven aan gebruikers, etc.). 

Graag verduidelijken: Is het toegestaan voor zulke **applicaties en diensten** om de gegevens te negeren? Bijvoorbeeld door slechts een deel van de DCAT gegevens te verwerken (mits transparant en duidelijk is dat dat gedaan wordt).

**Comment by idevisser** [comment]
Nog in bewerking....
Voorgestelde aanpassing;

DCAT-AP NL definieert vier niveaus van vereisten voor ontvangers en aanbieders van gegevens. Daarbij geldt dat de niveaus alleen gelden voor de aanbieders.  In de volgende secties worden klassen en eigenschappen aangeduid als "verplicht", "aanbevolen", "optioneel" of conditioneel. Deze termen hebben de volgende betekenis:


Verplichte eigenschap:  een aanbieder MOET de informatie voor die eigenschap verstrekken.
Aanbevolen eigenschap: een aanbieder BEHOORT de informatie voor die eigenschap te verstrekken indien deze beschikbaar is.
Optionele eigenschap:  een aanbieder MAG de informatie voor die eigenschap verstrekken, maar is daartoe niet verplicht.
Conditionele eigenschap:  een aanbieder MOET de informatie voor die eigenschap verstrekken, indien de conditie van toepassing is.


Ontvangers MOETEN altijd in staat zijn om informatie over alle instanties van alle klassen en al hun eigenschappen te verwerken.

In de gegeven context betekent de term "verwerken" dat ontvangers binnenkomende gegevens MOETEN accepteren en deze gegevens op transparante wijze aan applicaties en diensten moeten leveren. Het impliceert noch schrijft voor wat applicaties en diensten uiteindelijk met de gegevens doen (parseren, converteren, opslaan, doorzoekbaar maken, weergeven aan gebruikers, etc.).

**Comment by skornsekj** [comment]
Volgende tekstuele aanpassing is toegevoegd in de 1ste alinea: '_Om volledig te voldoen aan DCAT-AP NL MOETEN ontvangers_. 

DCAT-AP NL definieert vier niveaus van vereisten voor ontvangers en aanbieders van gegevens. Daarbij geldt dat de niveaus alleen gelden voor de aanbieders. _Om volledig te voldoen aan DCAT-AP NL MOETEN ontvangers_ altijd in staat zijn om informatie over alle instanties van alle klassen en al hun eigenschappen te verwerken. In de volgende secties worden klassen en eigenschappen aangeduid als "verplicht", "aanbevolen", "optioneel" of conditioneel. Deze termen hebben de volgende betekenis:
