### ISSUE TITLE
Editorial: in 3.3.12 identifier staat een "vraag" (in feite een issue (nu deze dus): Vraag, heeft een identifier voor dataservice meerwaarde, is dit in te vullen vanuit bestaande metadata?

### ISSUE THREAD

**Issue by jambelien** [Geonovum/DCAT-AP-NL30#50]
Paragraaf: 3.3.12 identifier
Type issue: editorial
korte omschrijviing: aan het einde van de paragraaf staat nu: "Vraag, heeft een identifier voor dataservice meerwaarde, is dit in te vullen vanuit bestaande metadata?"
prioirteit issue: "must be resolved before public consultation" :-)
Voorgestelde oplossing, c.q. ter discussie: willen we deze vraag in het document laten staan? Daarnaast lijkt het me beter om het als een issue op te nemen (nu gedaan).

**Comment by skornsekj** [comment]
In werkgroep besproken dat we identifiers in dataservices op dezelfde manier behandelen als identifiers in dataset. Dat staat al goed in de tabellen in het respec document. 
Alleen de bovengenoemde tekst met de vraag in paragraaf 3..3.12 moet verwijderd worden.
