### ISSUE TITLE
Editorial: Links in tabellen van Klassen

### ISSUE THREAD

**Issue by RemieJanssen** [Geonovum/DCAT-AP-NL30#51]
3. Klassen

In de overzichtstabellen van hoofdstuk 3 verwijst de link in de Property kolom (vrijwel) altijd naar de link in de tweede kolom.
Misschien is het zinvoller om bij het klikken op de term te linken naar de beschrijving van de eigenschap op deze pagina zelf.
Dan kan een klikbare link voor de tweede kolom toegevoegd worden, die verwijst naar de beschrijving in de bron.

**Comment by skornsekj** [comment]
aangepast
