### ISSUE TITLE
Editorial: Beschrijving bereik

### ISSUE THREAD

**Issue by RemieJanssen** [Geonovum/DCAT-AP-NL30#52]
2.5 Omschrijving eigenschappen
> Bereik: Beschrijft de mogelijke waarden van de eigenschap.

Misschien goed om specifieker te zijn:
> Bereik: Het type (klasse of datatype) dat een waarde van deze eigenschap moet hebben.

Hierbij is ook https://github.com/Geonovum/DCAT-AP-NL30/issues/47 van belang

**Comment by idevisser** [comment]
aangepast
