### ISSUE TITLE
Editorial: Beschrijving kardinaliteit

### ISSUE THREAD

**Issue by RemieJanssen** [Geonovum/DCAT-AP-NL30#53]
2.5 Omschrijving eigenschappen
> Kardinaliteit: Geeft aan of de eigenschap 0, 1 of meerdere keren mag voorkomen. Hierbij wordt gebruik gemaakt van de schrijfwijze x..y, waarbij x het minimaal aantal voorkomens aangeeft en y het maximaal aantal. Bijvoorbeeld 1..n geeft aan dat de eigenschap een of meer keer mag voorkomen.

De term `1..n` wordt hier als voorbeeld behandeld, terwijl het eigenlijk een deel van de definitie betreft. Hoewel het redelijk gebruikelijke notatie is, zou het beter zijn dit stricter te definieren.

Notitie: Waarom wordt overigens afgeweken van de `1..*` notatie uit DCAT-AP?

**Comment by skornsekj** [comment]
Voorbeeld is verwijderd.
