### ISSUE TITLE
Editorial: Beschrijving waardelijst

### ISSUE THREAD

**Issue by RemieJanssen** [Geonovum/DCAT-AP-NL30#54]
2.5 Omschrijving eigenschappen
> Waardelijst: Verwijzing naar de codelijsten die van toepassing zijn.

Voor de uitleg van een waardelijst wordt hier een codelijst genoemd. De term codelijst wordt niet gedefinieerd, en ook nergens anders gebruikt.
Voorstel: definieer codelijst als dat daadwerkelijk de bedoeling was, of vervang door waardelijst.

**Comment by skornsekj** [comment]
Voorstel definitie waardelijst: Een lijst van mogelijke waarden voor een eigenschap.

**Comment by skornsekj** [comment]
verwerkt
