### ISSUE TITLE
Editorial: gebruik ongedefinieerde namespaces

### ISSUE THREAD

**Issue by RemieJanssen** [Geonovum/DCAT-AP-NL30#56]
Betreft (bv) 3.1 Dataset - dcat:Dataset

Er wordt gerefereerd naar [eli:LegalResource](http://data.europa.eu/eli/ontology#LegalResource), maar de namespace `eli` staat niet in de tabel met namespaces.

Voorstel: Voeg alle gebruikte namesapces toe aan de tabel in hoofdstuk 1.1 Namespaces

**Comment by idevisser** [comment]
aangepast
