### ISSUE TITLE
Editorial: namespaces in URI kolom in klasse tabellen

### ISSUE THREAD

**Issue by RemieJanssen** [Geonovum/DCAT-AP-NL30#57]
Betreft 3. Klassen

In de kolom URI van iedere overzichtstabel van de klassen wordt de volledige uri gegeven. Er is echter ook een lijst van namespaces gedefinieerd die in dit document gebruikt kunnen worden. Zou het voor het overzicht niet beter zijn die namespaces hier ook te gebruiken?

De volledige URL/URI kan als klikbare link toegevoegd worden. Zie ook https://github.com/Geonovum/DCAT-AP-NL30/issues/51

**Comment by idevisser** [comment]
De volledige URL/URI kan als klikbare link toegevoegd worden. Zie ook https://github.com/Geonovum/DCAT-AP-NL30/issues/51 is opgelost.

namespace toevoegen komt overzichtelijkheid niet ten goede
