### ISSUE TITLE
Inhoudelijk: Waardelijst license definiëren en opnemen

### ISSUE THREAD

**Issue by jambelien** [Geonovum/DCAT-AP-NL30#58]
Paragraaf 3.2.14 en 3.3.16 licence (en overig gebruik eigenschap licence)
Type issue: inhoudelijk
Korte omschrijving: in de beuwste paragraaf wordt de volgende zin(sconstructie) gebruikt: "In het geval geen (her)gebruik volgens een CC licentie mogelijk is, mag de waarde ‘niet-open' gebruikt worden."
Hoe wordt de waarde 'niet open' gekozen, dan wel wordt dit "ingetypt"? Is dit een waarde die deel uitmaakt van een drop-down of radio button (met onderliggende code/value opdat het in verschillende talen blijft werken)?
Voorgestelde aanpassing: voor een keuze optie gaan en niet vrije tekst en dat in document als zodanig duidelijk weergeven.
Prioriteit issue: must have

**Comment by idevisser** [comment]
Voorstel tot aanpassing;

hiervoor wordt een waardelijst gedefinieerd. Als deze er is kan de verwijzing naar de waardelijst worden opgenomen in het profiel

**Comment by skornsekj** [comment]
NOOT toegevoegd.

**Comment by idevisser** [comment]
link naar waardelijst opgenomen

**Comment by HNeikes** [comment]
Ik probeerde net de waardelijst te bekijken; helaas werkt de link niet
https://definities.geostandaarden.nl/dcat-ap-nl/id/waardelijst/licenties

![image](https://github.com/Geonovum/DCAT-AP-NL30/assets/50417877/b2171421-185f-4d6a-aceb-3613f35b58d7)

**Comment by idevisser** [comment]
Hallo Hanna, graag nog even geduld, de waardelijst komt op die locatie in augustus beschikbaar. (het lukt me niet meer voor mn vakantie)
