### ISSUE TITLE
Editorial: Ranges van eigenschappen met datetime waarden

### ISSUE THREAD

**Issue by RemieJanssen** [Geonovum/DCAT-AP-NL30#60]
Hoofdstuk 3. Klassen

De ranges van eigenschappen zoals modification date en release date moeten verder gespecificeerd worden dan alleen Literal (rdfs:Literal en niet sh:Literal, zie https://github.com/Geonovum/DCAT-AP-NL30/issues/59). DCAT-AP gebruikt hiervoor de term `Temporal Literal` (https://semiceu.github.io/DCAT-AP/releases/3.0.0/#TemporalLiteral), een soort Literal met een beperkte set opties voor de datatype IRI.

Wellicht is het een goed idee om dat concept plus het gebruik ervan over te nemen?

**Comment by idevisser** [comment]
In DCAT-AP 3.0, [Temporal Literal](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#TemporalLiteral) was introduced do cover the usual data types used for dates: xsd:gYear, xsd:gYearMonth, xsd:date, and xsd:dateTime as used in [DCAT 3](https://www.w3.org/TR/vocab-dcat-3/#Property:period_start_date)

Add Temporal Literal data type and replace (extend) the current approach using union of xsd:date and xsd:dateTime in all instances of:

end date (dcat:endDate)
start date (dcat:startDate)
release date (dct:issued)
update / modification date (dct:modified)
creation date (dct:created)
listing date (dct:issued)
Category scheme release date (dct:issued)

**Comment by skornsekj** [comment]
Aangepast
