### ISSUE TITLE
Inhoudelijk: 3.5.4 language in tabel paragraaf 3.5 heeft optionaliteit O, moet dat niet A zijn (of V en dan ook kardinaliteit aanpassen naar 1..n)?

### ISSUE THREAD

**Issue by jambelien** [Geonovum/DCAT-AP-NL30#61]
Paragraaf 3.5 tabel en paragraaf 3.5.4 language
Type issue: optionaliteit is in meeting 15-02-2024 besproken en zou van O naar tenminste A gaan (en eventueel zelfs V)
Dit staat in mijn aantekeningen. Dus graag check door groep/review team!
Prioriteit issue: Must-have
Voorgestelde oplossing: op basis van check door andere team-leden O aanpassen naar A of V (en indien V dan kadrinaliteit ook naar 1..n)

**Comment by idevisser** [comment]
Voorgestelde aanpassing;
Verplicht en kardinaliteit van 1..n
