### ISSUE TITLE
Editorial: Access rights mist opties

### ISSUE THREAD

**Issue by RemieJanssen** [Geonovum/DCAT-AP-NL30#62]
https://geonovum.github.io/DCAT-AP-NL30/#access-rights
> Deze eigenschap bevat informatie die aangeeft of de dataset openbaar toegankelijk is, toegangsbeperkingen heeft of niet openbaar is. 

Het voorgestelde vocabulair heeft meer dan de 3 opties gegeven in deze beschrijving. Het zou fijn zijn als de beschrijving matcht met het beoogde gebruik van het vocabulair.

Daarbovenop lijkt het erop dat DCAT-AP de range van deze eigenschap vrijer laat. Het geeft namelijk expliciet de optie om ook andere waarden te gebruiken zoals die uit [Eprints Access Rights Vocabulary Encoding Scheme](http://purl.org/eprint/accessRights/) (zie https://www.w3.org/TR/vocab-dcat-3/#license-rights). Als deze extra restrictie bovenop DCAT-AP de bedoeling is, dit graag aangeven hier.

**Comment by skornsekj** [comment]
In de usage notes van ['Controlled vocabularies to be used'](https://semiceu.github.io/DCAT-AP/releases/3.0.0/#controlled-vocs) in DCAT-AP wordt aangegeven dat één van de de volgende waarden gebruikt moet worden: public; restricted; non-public. 
Dit is toegevoegd aan de beschrijving van de property access_rights bij de klassen dataset en dataservice.
