### ISSUE TITLE
Editorial: Broken link in applicable legislation

### ISSUE THREAD

**Issue by RemieJanssen** [Geonovum/DCAT-AP-NL30#63]
Betreft 3.1.2 applicable legislation

De link http://data.europa.eu/eli/reg_impl/2023/138/oj werkt niet. Er staat namelijk een spatie aan het einde, waardoor hij naar http://data.europa.eu/eli/reg_impl/2023/138/oj%20 verwijst.

**Comment by jambelien** [comment]
Kan worden gesloten, zelfde issue als #29

**Comment by RemieJanssen** [comment]
Oeps, die had ik gemist, excuses!
