### ISSUE TITLE
Editorial: Missende eli HVD waardelijst

### ISSUE THREAD

**Issue by RemieJanssen** [Geonovum/DCAT-AP-NL30#64]
5. Waardelijsten

De waardelijst http://data.europa.eu/eli/reg_impl/2023/138/oj voor HVD mist in de tabel in Hoofdstuk 5.

**Comment by idevisser** [comment]
Het is ook niet echt een waardelijst, maar een verwijzing naar het document.

de tekst bij applicable legislation is hierop aangepast;
Gebruik de referentie naar de officiële publicatie van de wetgeving. Voor HVD moet deze eigenschap de referentie naar de publicatie in ELI http://data.europa.eu/eli/reg_impl/2023/138/oj bevatten.
