### ISSUE TITLE
Missende ondersteunende klasse - vcard:Kind

### ISSUE THREAD

**Issue by RemieJanssen** [Geonovum/DCAT-AP-NL30#65]
4. Ondersteunende Klassen

Voor de vcard:Kind ondersteunende klasse wordt geen implementatieadvies gegeven. Het zou goed zijn deze klasse in hoofdstuk 5 toe te voegen en wat richtlijnen voor het gebruik ervan te geven. Bijvoorbeeld: welke onderklasse gebruiken we in welk geval, en welke eigenschappen van deze onderklassen zijn verplicht?

**Comment by idevisser** [comment]
De ondersteunende klassen waar geen toelichting bij is worden in een aparte paragraaf toegevoegd. 

Voor deze klasse maken we vooralsnog geen verdere toelichting.

**Comment by skornsekj** [comment]
verwerkt
