### ISSUE TITLE
Editorial: Broken link for hvdCategory

### ISSUE THREAD

**Issue by RemieJanssen** [Geonovum/DCAT-AP-NL30#66]
3.1.12 HVD Category

De link van `dcatap:hdvCategory` is kapot. Helaas lijkt dat de bedoeling omdat het in DCAT-AP-HVD ook zo is... 
Hier volgt een werkende link naar een beschrijving https://semiceu.github.io/uri.semic.eu-generated/DCAT-AP/releases/2.2.0-hvd/#Dataset.HVDCategory
Ik denk dat het goed is een werkende link te verschaffen naast de niet werkende officiele link.

Wellicht is het ook aardig om bij de beschrijving van deze eigenschap te noemen dat hij niet uit DCAT-AP, maar uit de DCAT-AP-HVD annex komt.

**Comment by idevisser** [comment]
De links komen uit de SHACL van de EU. De aanpassing zal daar doorgevoerd moeten worden, wij kunnen het daar automatisch uit genereren.

**Comment by skornsekj** [comment]
De link van dcatap:hdvCategory werkt inmiddels.

**Comment by skornsekj** [comment]
Issue is opgelost.
