### ISSUE TITLE
Vraag: Dataset eigenschap restrictie - language

### ISSUE THREAD

**Issue by RemieJanssen** [Geonovum/DCAT-AP-NL30#67]
3.1.19 language
>  Language heeft de beperking (ten opzichte van DCAT-AP) dat deze eigenschap alleen de waarde kan bevatten van de taal van de tekstuele waardes in de dataset.

Vraag: Wat betekent deze extra restrictie? Is het dat een dataset een language mag hebben slechts wanneer die taal ook daadwerkelijk in de textuele delen van de dataset voorkomt? Waarvoor dient deze restrictie?

**Comment by idevisser** [comment]
Deze restrictie bakent het gebruik van de property af. De waarde heeft alleen betrekking op de tekstuele waardes in de dataset zelf en niet op de taal van de metadata.

**Comment by idevisser** [comment]
Voorstel tot aanpassing; 

Language heeft de beperking (ten opzichte van DCAT-AP) dat deze eigenschap alleen de waarde kan bevatten van de taal van de tekstuele waardes in de dataset. Deze restrictie bakent het gebruik van de property af. De waarde heeft alleen betrekking op de tekstuele waardes in de dataset zelf en niet op de taal van de metadata.

**Comment by idevisser** [comment]
ook opnemen bij de andere klassen, distributie, dataservice, catalog

**Comment by idevisser** [comment]
aangepast
