### ISSUE TITLE
Inhoudelijk: Gebruik van distributie status vocabulaire voor dataset status.

### ISSUE THREAD

**Issue by RemieJanssen** [Geonovum/DCAT-AP-NL30#68]
3.1.33 status
> Gebruik hiervoor een waarde uit [EU Vocabularies Distribution Status](http://publications.europa.eu/resource/authority/distribution-status)

Merk op dat dit vocabulaire bedoeld is voor distributies. In DCAT-AP wordt het dan ook alleen voor distributies gebruikt, en niet voor datasets. Is dit een bedoelde uitbreiding van de scope van dit vocabulair?

**Comment by idevisser** [comment]
Dit is inderdaad als uitbreiding op de scope bedoelt.

**Comment by RemieJanssen** [comment]
De beschrijving van de termen gaat wel heel expliciet over dataset distributies. Misschien staan ze er in Europa voor open om de beschrijving aan te passen zodat hij ook op datasets toepasbaar is? Er staat dat ze bijdragen via een reviewproces kunnen accepteren: https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/distribution-status

Nog een kleine vraag erbij: Waarom is er uberhaupt voor gekozen de status-eigenschap op te nemen voor datasets? Is die voor de aansluiting op een andere standaard van belang?

**Comment by idevisser** [comment]
Gaat het je alleen om de naamgeving van de vocabulaire,  EU Vocabularies Distribution Status, of ook om de waarden die daar in zijn opgenomen?

Status wordt opgenomen voor datasets, omdat die anders kan zijn dan dan de status van de distributie.

**Comment by RemieJanssen** [comment]
Het gaat me vooral om de naamgeving inderdaad, de waarden zijn makkelijk te "misbruiken" voor datasets. In principe passen de waarden wel goed voor datasets, maar de waarden zijn expliciet gedefinieerd voor Distributies, en datasets zijn geen distributies in DCAT.

Het zou mijns inziens dus beter zijn een nieuwe lijst te maken die specifiek is bedoeld voor datasets, of te vragen of het vocabulair 'EU Vocabularies Distribution Status' gegeneraliseerd kan worden. Bijvoorbeeld tot iets als 'EU Vocabularies Status', met dan dezelfde waarden als 'EU Vocabularies Distribution Status' nu heeft.

**Comment by RemieJanssen** [comment]
Eens met je voorstel, het bestaan van die lijst maakt het makkelijk op te lossen :)

**Comment by skornsekj** [comment]
Bij dataset status wordt nu verwezen naar [EU Vocabularies Dataset Status](http://publications.europa.eu/resource/authority/dataset-status)

**Comment by skornsekj** [comment]
aangepast
