### ISSUE TITLE
Editorial: Dataset dcat:version beschrijving

### ISSUE THREAD

**Issue by RemieJanssen** [Geonovum/DCAT-AP-NL30#70]
3.1.39 version
> De versie-indicator (naam of identificatie) van een bron.

In dit geval is de 'bron' altijd het object zelf, en dat is een `dcat:Dataset`.
Waarschijnlijk erin geslopen omdat de omschrijving is gehaald uit DCAT-AP, die het heeft gehaald uit [6.4 Class: Cataloged Resource](https://www.w3.org/TR/vocab-dcat-3/#Property:resource_version)? De eigenschap is namelijk oorspronkelijk alleen gedefinieerd voor de superklasse Cataloged Resource, en niet voor Dataset specifiek.

Voorstel:
> De versie-indicator (naam of identificatie) van de dataset.

**Comment by idevisser** [comment]
aangepast
