### ISSUE TITLE
Editorial: Dataset adms:versionNotes

### ISSUE THREAD

**Issue by RemieJanssen** [Geonovum/DCAT-AP-NL30#71]
3.1.40 version notes
> Een beschrijving van de verschillen tussen deze versie en **een eerdere** versie van de dataset.

verander in 
> Een beschrijving van de verschillen tussen deze versie en **de vorige** versie van de dataset.

Zie de definitie in DCAT: https://www.w3.org/TR/vocab-dcat-3/#Property:resource_version_notes

**Comment by idevisser** [comment]
aangepast
