### ISSUE TITLE
Incorrecte voorbeelden

### ISSUE THREAD

**Issue by RemieJanssen** [Geonovum/DCAT-AP-NL30#72]
3.1.42 Voorbeelden

Het voorbeeld van de dataset in Voorbeeld 1 (https://geonovum.github.io/DCAT-AP-NL30/#example-1) is onvolledig, en daardoor incorrect als het gaat om DCAT-AP-NL. Er mist bijvoorbeeld 'access rights'.

**Comment by idevisser** [comment]
De voorbeelden zijn nog niet volledig, deze worden nog aangepast.

**Comment by idevisser** [comment]
aangepast
