### ISSUE TITLE
Editoriaal: Structuur van het toepassingsprofiel

### ISSUE THREAD

**Issue by Bakkej** [Geonovum/DCAT-AP-NL30#75]
**Paragraaf**: 2.1
**Type**:
Editoriaal
**Omschrijving**:
Ik weet niet of de uitleg van klassen en eigenschappen echt nodig zijn; als we dat wel vinden moeten ze kloppen. 

Het is raar om te stellen dat klassen dingen zijn op het internet. Een klasse kan bedacht worden zonder dat deze op 'het internet' te vinden is (ook wanneer iets in RDF gespecificeerd is hoeft het nog niet op het internet te zijn). 
Ook doen de voorbeelden, zoals 'een persoon', vermoeden dat een klasse iets is zoals een specifiek object zoals ik (want ik ben *een* persoon). Het is juist een abstractie daarvan. _Een klasse beschrijft (complexe) dingen met vergelijkbare characteristieken zoals personen, organisaties, datasets ...._

Het stellen dat sommige eigenschappen klassen zijn is ook raar, in het model koppel je ze misschien aan een klasse; in de data verwijzen ze naar iets wat getypeerd is aan de hand van een bepaalde klasse. Volgens mij willen we aangeven dat sommige eigenschappen beschreven worden met een literal (deze eigenschappen zijn ookwel owl:DatatypeProperty) en andere zijn relaties naar andere objecten (een owl:ObjectProperty).

**Prioriteit**:
must-have

**Comment by idevisser** [comment]
aangepast
