### ISSUE TITLE
Editoriaal: vertaal controlled vocabulary

### ISSUE THREAD

**Issue by Bakkej** [Geonovum/DCAT-AP-NL30#76]
**Paragraaf**: meerdere
**Type**:
Editoriaal
**Omschrijving**:
Controlled vocabulary wordt gebruikt zonder dat het duidelijk is wat dat precies is; ook is het geen nederlandse term. Mijn voorstel is het gebruiken van de term "Begrippenkader" conform [SBB](https://profielstelselcatalogus.pldn.nl/#dfn-begrippenkader) waarin het als synoniem voor controlled vocabulary gezien wordt.
**Prioriteit**:
should-have

**Comment by idevisser** [comment]
Bij termen en definities een omschrijving toevoegen?

**Comment by idevisser** [comment]
aangepast
