### ISSUE TITLE
redactioneel commentaar: Should-have § 3.3 DataService e.v.

### ISSUE THREAD

**Issue by keestrautwein** [Geonovum/DCAT-AP-NL30#79]
In alle Engelstalige documentatie wordt "DataService" als twee losse woorden geschreven. In het Nederlands schijven we gegevensdienst of mogelijk dataservice, maar als we verwijzen naar de standaard of het gebruik van de term in het engels stel ik voor consequent de correct schrijfwijze "Data Service" te gebruiken.

**Comment by idevisser** [comment]
even uitzoeken hoe we dat voor het hele document in een keer kunnen aanpassen

**Comment by skornsekj** [comment]
aangepast
