### ISSUE TITLE
Inhoudelijk: Should-have § 3.3 DataService e.v.

### ISSUE THREAD

**Issue by keestrautwein** [Geonovum/DCAT-AP-NL30#80]
De tweede zin van de twee slotzinnen van de eerste alinea is niet correct:
Over de twee slotzinnen:
"In deze nieuwe versie van het toepassingsprofiel is de dataservice klasse optioneel. Dat betekent dat het mogelijk blijft om dataservices te beschrijven met de klasse Distributie."

De klasse DataService is niet optioneel omdat die ook met Distribution beschreven kan worden, maar omdat niet iedere DCAT beschrijving een data service bevat. 

The is correct dat in DCATv1.x kon een Data Service niet direct beschreven worden. Om oude DCAT beschrijvingen te ondersteunen zijn DCATv2 en DCATv3 backwards compatible en kunnen data service zonder Data Service beschreven worden, maar dat wordt afgeraden voor nieuwe beschrijvingen. Nieuwe beschrijvingen of beschrijvingen die worden bijgewerkt moeten DataService gebruiken voor gegevensdiensten

Mijn voorstel voor een nieuwe tekst:

"In deze nieuwe versie van het toepassingsprofiel is de dataservice klasse optioneel. 

Merk op dat DCATv2 en DCATv3 backwards compatible zijn met DCATv1.x  waarin Data Service niet beschreven kon worden. Bestaande beschrijvingen van Data Services binnen DCATv1.x blijven dus ondersteund. Voor nieuwe DCAT beschrijvingen of bestaande beschrijvingen die worden omgeschreven naar DCATv2 of DCATv3, MOET de klasse Data Service gebruikt worden om gegevensdiensten te beschrijven"

**Comment by idevisser** [comment]
aangepast
