### ISSUE TITLE
Inhoudelijk 3 .1 Dataset:  Definitie/beschrijving Dataset

### ISSUE THREAD

**Issue by keestrautwein** [Geonovum/DCAT-AP-NL30#81]
De tekst waarmee een Dataset wordt beschreven is niet geheel correct:
"Een dataset is een zinvolle verzameling van samenhangende gegevens, die beheerd of gepubliceerd wordt door één organisatie, en in één of meer formaten beschikbaar of downloadbaar is."

Een Dataset kan Distributies hebben, maar dat hoeft niet. Een Dataset kan onderdeel uitmaken van een Data Service of een Dataset kan bestaan uit Data Services. Daarmee is de beschrijving hierboven niet correct.

Ook de term "zinvol" vind ik lastig. We zouden kunnen uitleggen  dat bepalen van een Dataset volgens criteria van de opsteller gebeurt, maar dat hoort misschien niet op deze plek.

Ik zou de tekst wijzigen in:
"Een dataset is een verzameling van samenhangende gegevens, die beheerd of gepubliceerd wordt door één organisatie"

Eventueel kan daar aan worden toegevoegd:
"Een Dataset kan beschikbaar zijn via distributies of gegevensdiensten (Data services)"

**Comment by idevisser** [comment]
Voorstel is om het als volgt op te nemen;

Een dataset is een verzameling van samenhangende gegevens, die beheerd of gepubliceerd wordt door één organisatie.  Een Dataset kan beschikbaar zijn via distributies of Data services.

**Comment by idevisser** [comment]
aangepast
