### ISSUE TITLE
Editoriaal: naamgeving standaard

### ISSUE THREAD

**Issue by Bakkej** [Geonovum/DCAT-AP-NL30#82]
Op veel plekken wordt de standaard aangeduidt met `DCAT-AP NL`, dit moet `DCAT-AP-NL` zijn, wat in lijn is met de naamgeving van andere landelijke uitwerkingen van DCAT-AP.

**Comment by idevisser** [comment]
pakken we op

**Comment by idevisser** [comment]
even kijken of we dit in éé'n keer in hele document kunnen oplossen
