### ISSUE TITLE
Editoriaal: links tussen tabellen en verdere toelichtingen

### ISSUE THREAD

**Issue by Bakkej** [Geonovum/DCAT-AP-NL30#83]
Het zou mooi zijn als ik vanuit een tabel (zoals die in praragraag 3.1) snel kan doorklikken naar de beschrijving van de eigenschap (zoals https://geonovum.github.io/DCAT-AP-NL30/#creator).

prioriteit: nice to have

**Comment by idevisser** [comment]
Is toegevoegd
