### ISSUE TITLE
Inhoudelijk: beschrijving description

### ISSUE THREAD

**Issue by Bakkej** [Geonovum/DCAT-AP-NL30#84]
In de beschrijving van description (3.1.7, 3.3.6, 3.4.6) wordt gesteld dat dit gegeven bepalend is voor de vindbaarheid van een resource. Dit lijkt mij te kort door de bocht. De vindbaarheid van een resource wordt bepaald door de kwaliteit van de beschikbare metadata over de resources en de gerelateerde resources. Bijvoorbeeld, hoe beter we een bepaalde thema (een begrip) beschrijven hoe meer ingangen we creëren om een dataset te vinden die hieraan gekoppeld is.

Door te stellen dat de description bepalend is voor de vindbaarheid doet af aan het nut en noodzaak van de andere kenmerken die beschreven kunnen worden.

**Comment by idevisser** [comment]
De tekst wordt hierop aangepast

**Comment by idevisser** [comment]
aangepast in de verschillende klassen
