### ISSUE TITLE
Language tags: welke waardelijst

### ISSUE THREAD

**Issue by skornsekj** [Geonovum/DCAT-AP-NL30#85]
Paragraaf: 2.6. Meertaligheid
Type:
Inhoudelijk
Omschrijving:
Welke waardelijst voor language tags gaan we gebruiken.  Opties zijn:  
- [ISO 639-1](https://id.loc.gov/vocabulary/iso639-1.html) (two-letter), and corresponding IRI SHOULD be used; 
- [ISO 639-2](https://id.loc.gov/vocabulary/iso639-2.html) (three-letter), and corresponding IRI SHOULD be used;

**Comment by skornsekj** [comment]
Voorstel: Gebruik van de 2-letter code [ISO 639-1](https://id.loc.gov/vocabulary/iso639-1.html).

**Comment by idevisser** [comment]
aangepast in doc
