### ISSUE TITLE
Editorial: 3.1.6 dataset distribution

### ISSUE THREAD

**Issue by skornsekj** [Geonovum/DCAT-AP-NL30#88]
Paragraaf: 3.1.6
Type:
Editoriaal
Omschrijving:
datatset distribution is conditioneel verplicht voor HVD. De reden van de conditie is nu niet opgenomen in de tekstuele beschrijving in. 
Voorstel: Volgende tekst toevoegen. 'Deze eigenschap is verplicht, als de dataset onder de HVD uitvoeringsverordening valt.'
Prioriteit:
Must-Have

**Comment by idevisser** [comment]
aangepast
