### ISSUE TITLE
3.2.20  distribution rights

### ISSUE THREAD

**Issue by idevisser** [Geonovum/DCAT-AP-NL30#92]
rights staat in overzichts tabel op conditioneel, bij de eigenschap is geen conditie opgenomen...

**Comment by skornsekj** [comment]
@idevisser in het NL profiel hebben we momenteel license (distributie) en accessRights (dataset) al verplicht. De vraag is of daarmee niet al aan de DGA vereisten wordt voldaan.

**Comment by skornsekj** [comment]
Bij de eigenschap is de conditie opgnomen. 
'Deze eigenschap is verplicht, als de dataset onder de Data Governance Act (DGA) valt.'

Verwerkt
